### ISSUE TITLE
php-debug config no longer valid

### ISSUE THREAD

**Issue by synthecypher** [gwomacks/php-debug#100]
I attempted to copy and paste the suggested config settings for `php-debug` into my `config.cson` but it just deleted the `PathMaps` variable containing an array of objects. I assume it's not considered valid syntax.

Can we update this with a valid config settings.

**Comment by derekderaps** [comment]
This issue duplicates #99. And I believe the real problem is in Atom core. I made an issue there: https://github.com/atom/atom:10345

**Comment by cchamplin** [comment]
This has been adjusted with the latest release. The new format is "remotepath;localpath".
