### ISSUE TITLE
Cyrillic symbols as variables values in debug panel

### ISSUE THREAD

**Issue by ilyachase** [gwomacks/php-debug#104]
Threre's a problem with cyrillic symbols when debugging:
![1](https://cloud.githubusercontent.com/assets/1961077/12156389/9e8942f8-b4ec-11e5-9c9a-19cdd2543c2b.jpg)
May be it's a problem with xdebug?

**Comment by cchamplin** [comment]
Hopefully fixed in v0.2.2 - Released Today
