### ISSUE TITLE
Minor bug: arrow operators are being encoded.

### ISSUE THREAD

**Issue by Gert-dev** [gwomacks/php-debug#106]
Hello

It seems that in the latest version, the arrow operator is being encoded under the *Locals* item, e.g.:

```php
$test->*SplObjectStorage*storage
```

becomes

```php
$test-&amp;gt;*SplObjectStorage*storage
```

Thanks in advance

**Comment by cchamplin** [comment]
Should be resolved in today's release, Thanks!
