### ISSUE TITLE
Problems with atom-autocomplete-php

### ISSUE THREAD

**Issue by rugk** [gwomacks/php-debug#110]
XDebug always seems to stop at a script from [`atom-autocomplete-php`](https://atom.io/packages/atom-autocomplete-php) when I save the file.

![autocompleteerror](https://cloud.githubusercontent.com/assets/11966684/12535807/f1e4478a-c28f-11e5-967e-d90081c2538f.PNG)

Also reported [there](https://github.com/Peekmo/atom-autocomplete-php/issues/229).

**Comment by rugk** [comment]
Any news?

**Comment by cchamplin** [comment]
I have not put time into investigating this but I'll see if I can look into it if it's still an issue.

**Comment by cchamplin** [comment]
The package has been rewritten almost entirely as of v0.3.0. I hope this should resolve some of the older issues, if not please reopen.
