### ISSUE TITLE
Consistent context menu

### ISSUE THREAD

**Issue by rugk** [gwomacks/php-debug#112]
Many things you find in the context menu when right-clicking on a breakpoint (e.g. [this](https://github.com/gwomacks/php-debug/issues/95)) are main items, so they are in no sub-menu. However "Toggle Breakpoint" and "Toogle Debugging" are sub-menus in the "PHP-Debug" menu.

You should be consistent and move all context menu entries inside of the "PHP-Debug" menu. (My context menu is already incredible large thanks to many packages I installed)

**Comment by cchamplin** [comment]
The thought behind this, was that if you are right clicking a breakpoint you've already narrowed your "context" to be pretty specific, so we're trying to guess that you might want to adjust breakpoint conditions, etc. If there is community desire to have this adjusted we can make that change.
