### ISSUE TITLE
[Feature] It would be nice to be able to specify the IP address of xdebug

### ISSUE THREAD

**Issue by dschissler** [gwomacks/php-debug#115]
I'm using Atom on OSX and developing on an Ubuntu virtual machine.  It doesn't look like there is a setting to specific the xdebug machine and so I will have to use SSH port forwarding.

**Comment by jamesmcminn96** [comment]
Any reason why you closed this? Would be nice to have feature.

**Comment by cchamplin** [comment]
Addressed in #166 and PR #167
