### ISSUE TITLE
Need some help to work with Docker container

### ISSUE THREAD

**Issue by RobbeR** [gwomacks/php-debug#117]
Hi,

I'm just started to use Atom (as a replacement of NetBeans), and trying to setup the debugger with my system which is run in a Docker container. xdebug successfully installed inside the dockerVM (working fine with NetBeans), the VM has an IP address: 192.168.99.100. I just setting up in my hosts file: 192.168.99.100 mysystem.local

Then I installed this plugin in Atom, installed xdebug-helper to Chrome, but the debugging still doesnt work.
In xdebug-helper, needs to setup an "IDE key" or "sessionkey". These are some default values (Eclipse, Netbeans, etc), but what is the Atom's IDE Key?

Thanks in advance,
R

**Comment by cchamplin** [comment]
I realize it's been months since you opened this issue, but do you still need assistance with this. Your question is fairly specific and I'm not sure if I'll be able to provide much support.

**Comment by RuZniki** [comment]
Atom's IDE Key xdebug.atom http://stackoverflow.com/questions/35865492/atom-xdebug-setup
