### ISSUE TITLE
Feature request - do not break on suppressed errors

### ISSUE THREAD

**Issue by maaarghk** [gwomacks/php-debug#121]
The `@` symbol can be used to [suppress errors in PHP](http://php.net/manual/en/language.operators.errorcontrol.php).

Example of a suppressed error, from magento:

```php
$result = @vsprintf($translated, $args);
```

Ideally the debugger would automatically continue in this case.

**Comment by cchamplin** [comment]
I believe this is likely an issue with xdebug, or dbgp. As a quick fix though you should be able to turn off that particular exception from breaking by disabling breaking on warnings in the php-debug settings.

**Comment by istian** [comment]
hi @cchamplin, 

I'd like to know thw workaround.  Can you please paste the example settings? 

Thanks!

**Comment by cchamplin** [comment]
Should be unchecking the box for breaking on php exceptions or warnings/notices in the php-debug config inside atom.
