### ISSUE TITLE
Readme should say where to put config

### ISSUE THREAD

**Issue by ahnbizcad** [gwomacks/php-debug#126]
There is no indication in the readme saying where or which file to put 

`xdebug.remote_enable=1
xdebug.remote_host=127.0.0.1
xdebug.remote_connect_back=1    # Not safe for production servers
xdebug.remote_port=9000
xdebug.remote_handler=dbgp
xdebug.remote_mode=req
xdebug.remote_autostart=true`

**Comment by Sogl** [comment]
`php.ini` of course:
https://xdebug.org/docs/install
