### ISSUE TITLE
Cyrillyc data shows wrong

### ISSUE THREAD

**Issue by BedwaRe** [gwomacks/php-debug#128]
I have some troubles with the cyrillyc data. When debugging in Atom.

Instead of:
`'number' => string '4251:ВЛ,2915:СД,18125:КС' (length=30)`
I get:
`$_GET['number']"4251:PP,2915:P!P,18125:PP!"`

Everywhere i can check i use utf-8. What is problem?

swared@z930:~$ atom -v
1.4.2
swared@z930:~$ uname -a
Linux z930 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u3 (2016-01-17) x86_64 GNU/Linux

xdebug support	enabled
Version	2.4.0RC4

**Comment by cchamplin** [comment]
Related to other UTF8 issues with xml parsing and xdebug. Unfortunately there is no fix.
