### ISSUE TITLE
future plans and naming conventions

### ISSUE THREAD

**Issue by sillyslux** [gwomacks/php-debug#131]
I have already made an error panel for the table-like panel in the panel view and fixed some minor bugs for quick package reloading.  @cchamplin and i agreed that i should have done different PRs for debugging, cleanup and new functionality, so i've closed the PR and will prepare new ones, i think.
But before i start, are there any conventions i should follow and what are the plans for the future? Is it supposed to one day become as nice and feature-rich like the php-debugger i've seen in phpStorm?

Since i've tried php-debug two days ago i started digging through the code, i ran into some bugs and lot's of missing functionality. I've made a resizable table (same html structure, no additional libs), an error message panel in that table, a new button for session detach (stop button now only aborts script execution), but most of the time i tried to understand what things do and the how's and where's and to be honest, it all seems like one big mess to me.
There's misplaced functionality, naming conventions that hurt(me), even useless code (who can tell what /lib/php-debug-panel-view.coffee does).
Before i try to immerse myself and do everything twice or even waste my time for >/dev/null, i thought it's best to first ask about the project maintainers standpoint on file naming conventions, class naming conventions and structures in general.
I mean look at this: i have the editor open with 2 panes and one pane has 6 open tabs, it looks like this:
/php-debug... **x**\ /php-debug... **x**\ /php-debug... **x**\ /php-debug... **x**\ /php-debug... **x**\ /php-debug... **x**\
and the open files are:
lib/breakpoint/php-debug-breakpoint-view.coffee
styles/php-debug.atom-text-editor.less
styles/php-debug.less
lib/php-debug.coffee
lib/php-debug-panel-view.coffee
lib/status/php-debug-status-view.coffee
Now find the style file... with that, i won't work.
Then if i find the file i'm searching for, i don't find the functions i expect or i have to scroll through 500 lines of code.
This probably doesn't read very nice, please don't think i want to be offensive or rude, because i really don't.

**Comment by cchamplin** [comment]
The naming conversions more or less follow the designs of the original author. I don't necessarily have a problem with them as they are, but it may be something that gets revisited for a future release.
