### ISSUE TITLE
Configure multiple vagrant pathmaps

### ISSUE THREAD

**Issue by minaeakhalil** [gwomacks/php-debug#136]
Is it possible to have multiple PathMaps for php-debug? I've tried to add the following into my configuration file:
"php-debug":
    PathMaps: [
      "/vagrant;/path/to/project1"
      "/vagrant;/path/to/project2"
      "/vagrant;/path/to/project3"
    ]

But when I try to run php-debug for the 3rd project, php-debug tries to load files from the top most project1 files.

**Comment by cchamplin** [comment]
You'll need to have different local and remote paths for each project for pathmaps to work correctly.

**Comment by ahnbizcad** [comment]
do you need commas separating them?

**Comment by minaeakhalil** [comment]
@ahnbizcad Yes, you need to separate them with commas.
