### ISSUE TITLE
Local debugging

### ISSUE THREAD

**Issue by vrxj81** [gwomacks/php-debug#137]
Hi I develop and run on my laptop locally, so I didn't configure PathMaps, I fgured i didn't need to because localpath and remotepath are the same?
When I set breakpoints and enable Xdebug, the breakpoints do not work.
What did I miss. If any more info is required, please ask.

**Comment by gigmaps** [comment]
+1

my config.cson for php-debug looks like:
```javascript
"php-debug":
  {
    ServerPort: 9000
  }
```

breakpoints _are_ working on my system 
however the php script is breaking on a random line of a file that runs on page load (eg Config.php) 
rather than the actual breakpoint specified breakpoint

**Comment by marcocastignoli** [comment]
@gigmaps did you solve the random file problem?

**Comment by gigmaps** [comment]
@marcocastignoli no unfoturtunately not - I've actually gone back to using Aptana with xdebug which (while being a slightly out of date IDE) is operating reliably.  I can try again and see if I have more success.

**Comment by marcocastignoli** [comment]
Same problem on two different machines with different configuration.

**Comment by gigmaps** [comment]
@marcocastignoli did you try unchecking all php exceptions listed at the bottom of php-debug settings (within Atom's Settings/Packages) as per #144 ?  haven't had time to reconfigure my server and try it myself yet but could be worth a shot.

**Comment by marcocastignoli** [comment]
I don't have any php exceptions...

**Comment by marcocastignoli** [comment]
Yes! It was just the configuration. Thank you, 3 days of testing and I didn't think about a setting view of the plugin. This is my first time with atom, I was thinking the confc file was the only way to configure Atom's packages... I think it's better to write a couple lines in the tutorial of this package about the setting menu, for the noobs like me. Thank you again @gigmaps
