### ISSUE TITLE
Only break at breakpoints

### ISSUE THREAD

**Issue by kimamil** [gwomacks/php-debug#138]
Hi gwomacks,

Thanks for this package, finally debugging made it to my atom installation.

I assumed, that when setting a breakpoint and start the script in the browser, the script would run until the breakpoint. Instead, I seem to have to click continue for every change of file or whatever. Unfortunately, debugging complex applications switching between hundreds of files (which all get opened) is no charm and is taking forever.

So I was wondering whether there's a setting or something, that the debugging only stops at set breakpoints, or opens files only when actually stepping in ...

Any hints, thoughts, ideas on that?

**Comment by caffeinelogic** [comment]
+1

Mine seems to do the same thing. Rather than halting at the line marked for debugging it seems to want to walk through the entire stack.

**Comment by UtamaruMonster** [comment]
+1

Same.

**Comment by cchamplin** [comment]
This is likely unrelated to php-debug and has something to do with your xdebug setup. Can you share your xdebug configuration?

**Comment by UtamaruMonster** [comment]
Here is my, this is stock brew installation, works perfectly with PhpStorm

zend_extension="/path-to-xdebug/xdebug.so"
xdebug.remote_enable=1
xdebug.remote_port=9000
xdebug.remote_handle=dbgp

even tried settings in description, same result.

**Comment by caffeinelogic** [comment]
Here is my current setting for my local vagrant instance. Let me know if I can give you any additional information about my environment.

xdebug.auto_trace = 0
xdebug.collect_includes = 1
xdebug.collect_params = 1
xdebug.collect_return = 0
xdebug.collect_vars = "Off"
xdebug.default_enable = "On"
xdebug.dump.COOKIE = ""
xdebug.dump.FILES = ""
xdebug.dump.GET = ""
xdebug.dump.POST = ""
xdebug.dump.REQUEST = ""
xdebug.dump.SERVER = ""
xdebug.dump.SESSION = ""
xdebug.dump_globals = 1
xdebug.dump_once = 1
xdebug.dump_undefined = 0
xdebug.extended_info = 1
xdebug.file_link_format = ""
xdebug.idekey = "VVVDEBUG"
xdebug.manual_url = "http://www.php.net"
xdebug.max_nesting_level = 100
xdebug.overload_var_dump = 1
xdebug.profiler_append = 0
xdebug.profiler_enable = 0
xdebug.profiler_enable_trigger = 1
xdebug.profiler_output_dir = "/tmp"
xdebug.profiler_output_name = "cachegrind.out.%t-%s"
xdebug.remote_autostart = 1
xdebug.remote_enable = 1
xdebug.remote_handler = "dbgp"
xdebug.remote_host = "192.168.50.1"
xdebug.remote_log = /srv/log/xdebug-remote.log
xdebug.remote_mode = "req"
xdebug.remote_port = 9000
xdebug.show_exception_trace = 0
xdebug.show_local_vars = 0
xdebug.show_mem_delta = 0
xdebug.trace_format = 0
xdebug.trace_options = 0
xdebug.trace_output_dir = "/tmp"
xdebug.trace_output_name = "trace.%c"
xdebug.var_display_max_children = -1
xdebug.var_display_max_data = -1
xdebug.var_display_max_depth = -1

**Comment by bluespuke** [comment]
Hi,

I'm having the same behaviour with TYPO3 6.2.19 on Ubuntu 15.10. Xdebug is connecting via Network, the files are on a samba share. PathMappings are good.

Here's my xdebug conf:

xdebug

xdebug support	enabled
Version	2.3.3
IDE Key	XDEBUG_ATOM
Supported protocols	Revision
DBGp - Common DeBuGger Protocol	$Revision: 1.145 $
Directive	Local Value	Master Value
xdebug.auto_trace	Off	Off
xdebug.cli_color	0	0
xdebug.collect_assignments	Off	Off
xdebug.collect_includes	On	On
xdebug.collect_params	0	0
xdebug.collect_return	Off	Off
xdebug.collect_vars	Off	Off
xdebug.coverage_enable	On	On
xdebug.default_enable	On	On
xdebug.dump.COOKIE	no value	no value
xdebug.dump.ENV	no value	no value
xdebug.dump.FILES	no value	no value
xdebug.dump.GET	no value	no value
xdebug.dump.POST	no value	no value
xdebug.dump.REQUEST	no value	no value
xdebug.dump.SERVER	no value	no value
xdebug.dump.SESSION	no value	no value
xdebug.dump_globals	On	On
xdebug.dump_once	On	On
xdebug.dump_undefined	Off	Off
xdebug.extended_info	On	On
xdebug.file_link_format	no value	no value
xdebug.force_display_errors	Off	Off
xdebug.force_error_reporting	0	0
xdebug.halt_level	0	0
xdebug.idekey	no value	no value
xdebug.max_nesting_level	256	256
xdebug.max_stack_frames	-1	-1
xdebug.overload_var_dump	On	On
xdebug.profiler_aggregate	Off	Off
xdebug.profiler_append	Off	Off
xdebug.profiler_enable	Off	Off
xdebug.profiler_enable_trigger	Off	Off
xdebug.profiler_enable_trigger_value	no value	no value
xdebug.profiler_output_dir	/tmp	/tmp
xdebug.profiler_output_name	cachegrind.out.%p	cachegrind.out.%p
xdebug.remote_autostart	Off	Off
xdebug.remote_connect_back	Off	Off
xdebug.remote_cookie_expire_time	3600	3600
xdebug.remote_enable	On	On
xdebug.remote_handler	dbgp	dbgp
xdebug.remote_host	10.0.0.66	10.0.0.66
xdebug.remote_log	no value	no value
xdebug.remote_mode	req	req
xdebug.remote_port	9000	9000
xdebug.scream	Off	Off
xdebug.show_exception_trace	Off	Off
xdebug.show_local_vars	Off	Off
xdebug.show_mem_delta	Off	Off
xdebug.trace_enable_trigger	Off	Off
xdebug.trace_enable_trigger_value	no value	no value
xdebug.trace_format	0	0
xdebug.trace_options	0	0
xdebug.trace_output_dir	/tmp	/tmp
xdebug.trace_output_name	trace.%c	trace.%c
xdebug.var_display_max_children	128	128
xdebug.var_display_max_data	512	512
xdebug.var_display_max_depth	3	3

**Comment by bluespuke** [comment]
FYI: I just installed and configured Eclipse with PHP Support, it seems to break at the exact same points... I guess i'm having a serious talk with Xdebug :D

**Comment by kimamil** [comment]
I have set the exact settings as in your readme.md

xdebug.remote_enable=1
xdebug.remote_host=127.0.0.1
xdebug.remote_connect_back=1    # Not safe for production servers
xdebug.remote_port=9000
xdebug.remote_handler=dbgp
xdebug.remote_mode=req
xdebug.remote_autostart=true

@bluespuke So you think it's a problem with xdebug?

**Comment by cchamplin** [comment]
@kimamil, with the way php-debug works it is almost certainly something on xdebug's side. We only send xdebug a list of breakpoint locations and types of exceptions to break on. The actual breaking is performed by xdebug.

**Comment by bluespuke** [comment]
Hi again,

When disabling Php Exception Notice and Strict Standards, Xdebug and php-debug are working as expected.

Thanks,
B!

**Comment by kimamil** [comment]
@bluespuke this solved it for me too. Seems like the code is not running through smoothly.

again - great package !!! Many Thanks!

**Comment by caffeinelogic** [comment]
@bluespuke your suggestion solved the issue for me as well. I had to disable Php Exception Warning as well as the ones you suggested. 

Thanks @kimamil for the great work!

**Comment by v1ctorf** [comment]
Hi, all! Thanks for the answers!

I've changed my php.ini here: error_reporting = E_ALL & ~E_NOTICE & ~E_STRICT & ~E_DEPRECATED & ~E_WARNING

Is this change right? is that you are recommending?

**Comment by v1ctorf** [comment]
@bluespuke Basically I did the same thing you did: My php.ini was restored and I've unabled all PHP Exceptions at my Atom/PHP-debug settings.
