### ISSUE TITLE
Wrong PHP

### ISSUE THREAD

**Issue by karneaud** [gwomacks/php-debug#139]
I've installed your package but when trying to run commands it seems to be using an old version of php on my machine located at usr/bin/php when my new version is on /usr/local/bin/php( running El Capitan)

Is there anyway to default to the new version?

**Comment by cchamplin** [comment]
php-debug does not natively invoke php at all. It waits for xdebug to connect to it on an open socket and then communicates with php that way.

**Comment by karneaud** [comment]
So you are saying that i should have a look at atom to see where this is coming from?

**Comment by cchamplin** [comment]
You may want to see if another atom plugin is causing your issue (a linter for example). You should be able to confirm it is not php-debug by disabling the plugin.

**Comment by karneaud** [comment]
Apparently starting Atom from the command line as opposed to starting it from the applications icon did the trick. Weird but works
