### ISSUE TITLE
Vagrant Setup

### ISSUE THREAD

**Issue by tillkruss** [gwomacks/php-debug#143]
How can I configure this package with Xdebug running on Vagrant? I tried setting it up, but without any luck. Working fine with PhpStorm.

**Comment by machei** [comment]
Also i have problem with Vagrant, also with other version unix too.

```
<- breakpoint_set -i 6 -t "line" -f "file:///vagrant/www/app/Lib/MessageQueue/Command/BroadcastCommand.php" -n 57
-> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="breakpoint_set" transaction_id="6" id="281660001"></response>
```

Server Ubuntu got message with prefix `file://`, it should be not on server unix.

my config's atom:
```
  "php-debug":
    PathMaps: [
      {
        local: "C:\\dev\\vargant\\www"
        remote: "/vagrant/www"
      }
    ]
    ServerPort: 9000

```

**Comment by machei** [comment]
Ah, I missed one line: `xdebug.remote_connect_back = 1` from php.ini and it worked.

https://github.com/gwomacks/php-debug/issues/125 - is helpfully for me.

**Comment by cchamplin** [comment]
Closing
