### ISSUE TITLE
dont stop execution on every contextual file change

### ISSUE THREAD

**Issue by pniederlag** [gwomacks/php-debug#144]
As it seems php-debug will automatically stop execution as soon as the execution context changes to a different file.

This is how i trigger the debugger:

php -dxdebug.remote_autostart=false -dxdebug.remote_host=remote.host -dxdebug.remote_enable=true lib/cli_example.phps

I'd like to see an option where I could just run the application until it it's a  certain line in a certain file.

**Comment by pniederlag** [comment]
Nice, it's probably just due to some errors/warnings or alike that are related to the files. Here's what I did to improve the setup for me:

- disable php-integrator-lint (as this added some errors as well)
- adapt settings of php-debug and unchecked all Php Exceptions

Now I can easily get to the point of the application where I'd like to debug.

**Comment by nahuelhds** [comment]
+1
I've been two hours looking for some way to avoid stopping at every involved file in the Stack.
Unchecking all Php Exceptions worked like a charm for me

**Comment by istian** [comment]
hi @nahuelhds,

Where can I uncheck PHP exception? Is it inside atom settings tab/panel? 

Thanks

**Comment by nahuelhds** [comment]
It's in the package config

**Comment by istian** [comment]
@nahuelhds, yep got it thanks!
