### ISSUE TITLE
Remote Windows path issue

### ISSUE THREAD

**Issue by jalandis** [gwomacks/php-debug#145]
I am debugging with a Vagrant Windows guest and Linux host setup.  With the following cson.json pathMap, incorrect paths are pointing to non-existent files.

```
PathMaps: [
  "C:/institutesRoot/;/home/jalandis/workspace/institutes/root/"
]
```

I was able to get working with the following edit to, php-debug/lib/helpers.coffee,  but am not 100% happy with what I have written.

```
exports.remotePathToLocal = (remotePath) ->
  pathMaps = atom.config.get('php-debug.PathMaps')
  adjustedPath = remotePath.replace('file://', '').replace(/\/([a-zA-Z]):/, '$1:')

  for pathMap in pathMaps
    [remote, local] = pathMap.split(';', 2)
    if adjustedPath.indexOf(remote) == 0
      return adjustedPath.replace(remote, local)

  return adjustedPath
```

The second replace was necessary due to an extra slash added to the path somewhere, **file:///C:/**.  I was unable to track down with the time I had.

**Comment by raptor235** [comment]
Hi @jalandis I was just looking at this... what base path are we supposed to specify? If we're running a VVV environments with multiple projects and domains.. what's the path supposed to be set to?

Sorry for the hijack

**Comment by cchamplin** [comment]
Is this still an issue?
