### ISSUE TITLE
Allow change of height for Stack, Context, Watchpoints, Breakpoints etc..

### ISSUE THREAD

**Issue by yareckon** [gwomacks/php-debug#148]
On my system, the big limitation using this package is the difficulty in seeing enough information in the tiny scrolling boxes which are not resizeable.  Can we get minimum a setting to change the height?  Even better would be a percent of the footer region, so that we can stretch it bigger as needed.

**Comment by cchamplin** [comment]
With the current versions of php-debug you should be able to click-drag-resize the entire panel for the debugger, is this functionality not working for you?

**Comment by nahuelhds** [comment]
+1 for this.

**Comment by cchamplin** [comment]
Heard no response on whether or not this is functioning, if it is not please reopen.

**Comment by nahuelhds** [comment]
This is working, just wanted to let you know
