### ISSUE TITLE
Improve breakpoint gutter line markers

### ISSUE THREAD

**Issue by gwomacks** [gwomacks/php-debug#15]
Make them a bit more visually pleasing, and correct their problems with multilines

**Comment by imperez** [comment]
On top of the above ideas any chance we can get an update that allows you to click in the gutter to create a breakpoint?

**Comment by Gert-dev** [comment]
I wanted to suggest the same. If the default gutter can't be used, you could perhaps register a custom gutter (that optionally is only visible when the php-debug panel is open, to avoid permanently hogging the space). This would really improve the user experience as you don't have to remember shortcuts or crawl through menu's. (It is also what IDE's usually do.)

**Comment by cchamplin** [comment]
Toggling breakpoints through the gutter should be available in v0.2.2 - Released Today
