### ISSUE TITLE
Random file, random line

### ISSUE THREAD

**Issue by marcocastignoli** [gwomacks/php-debug#151]
I had the same problem on two different machines: one with apache, one with nginx. So I think I'm soing something wrong with the configuration.
The debug always go to the wrong file/line, not the one with the breakpoint.

This is my php.ini
```
[xDebug]
zend_extension=/usr/lib/php5/20121212/xdebug.so
xdebug.remote_enable=1
xdebug.remote_host=127.0.0.1
xdebug.remote_port=9000
xdebug.remote_handler=dbgp
xdebug.remote_mode=req
xdebug.remote_autostart=1
```

And this is my config.cson
```
"php-debug":
  PathMaps: [
    "/localhost/;usr/share/nginx/www/"
  ]
  ServerPort: 9000
```

Am I doing it right?

**Comment by rafaelgaldencio** [comment]
Same here. Path maps are ok, the files are correct... xdebug_break works fine. Breaklines just don't work at all.

**Comment by marcocastignoli** [comment]
Just go to the settings (graphical, in the "php-debug" section) and uncheck all the option about php error debugging. Easy, there are no instructions, it took 3 days to figure out this simple trick...

**Comment by rafaelgaldencio** [comment]
Thanks. :smile: !

**Comment by cchamplin** [comment]
Closing this as it's configuration related.
