### ISSUE TITLE
Japanese value in variables

### ISSUE THREAD

**Issue by takaron1979** [gwomacks/php-debug#157]
Japanese value in variables is not properly encoded and cannot be read.
How can I solve this?

**Comment by cchamplin** [comment]
There are some issues around how xdebug encodes UTF8 characters and our ability to parse xml inside atom. At the moment I do not have a fix for this.

**Comment by tiibun** [comment]
If a servrer encoding is utf8, these changes can fix it.
https://github.com/gwomacks/php-debug/compare/master...tiibun:multibyte-variables

**Comment by cchamplin** [comment]
@tibun I believe that change may have caused the XML parser to break when attempting to parse certain characters. I'd have to recheck though.
