### ISSUE TITLE
Since atom 1.7, panel doesn't always pop up when debugging toggled.

### ISSUE THREAD

**Issue by maaarghk** [gwomacks/php-debug#158]
I've stepped through the atom debugger a bit, looks like the php-debug-unified-view.panel.visible property gets set to true correctly but the panel still does not appear. Closing atom and restarting is the only way to fix.

**Comment by yriveiro** [comment]
Same behaviour in 1.7.2

**Comment by cchamplin** [comment]
Can you check if this is still occurring with the latest release?

**Comment by cchamplin** [comment]
Never heard back on this. Closing for now.

**Comment by maaarghk** [comment]
yeah sorry, seems the email notification went to my spam. it stopped happening after atom 1.7.
