### ISSUE TITLE
Incorrect file Paths in Stack

### ISSUE THREAD

**Issue by heyyoyo** [gwomacks/php-debug#159]
I'm not sure what is wrong in my configuration.
All files appearing in the stack have a wrong path. So it is impossible to debug.
I'm using XDebug on windows in local(not inside VM)
All file paths have twice the webroot directory.
For example:
**C:\dir1\webroot\C:\dir1\webroot**\dir2\dir3\filename.ext

**Comment by tylkomat** [comment]
On Windows the `file:///` handler includes __three__ slashes which should be replaced in the `remotePathToLocal` not just two, then it works fine. I don't know how it is for Linux though.

**Comment by cchamplin** [comment]
This bug is several months old so I'm going to go ahead and close this for now. If you need this reopened please do so, with a copy of your php-debug configuration from atom.
