### ISSUE TITLE
💰 Willing to Pay for Setup Assistance 💰

### ISSUE THREAD

**Issue by tillkruss** [gwomacks/php-debug#161]
Anyone interested in helping me get this package working on OS X (and optionally with Vagrant)? Happy to pay by the hour.

**Comment by craigiswayne** [comment]
mail me: craigiswayne@gmail.com
also i don't want your money hahaha...


I can help with phpdebug on osx
just don't think this is the right place for this situation

**Comment by cchamplin** [comment]
It someone has recommendations or thoughts on how we can improve the readme, or the field labels in atom to make it easier to get the project setup and running correctly, I'm happy to accept input or a PR.
