### ISSUE TITLE
Execution does not begin

### ISSUE THREAD

**Issue by makinita** [gwomacks/php-debug#163]
Hi,
I have wamp server 3.0 with xdebug. If I visit my localhost:9000 the browser hangs, waiting for debug, ok, but back to atom editor the execution does not begin, and of course does not break at breakpoints. The cursor show a "forbidden" icon when I hover over "continue", "step over", ...  buttons.

Sorry for the picture, the screenshot removes the cursor.
![atom](https://cloud.githubusercontent.com/assets/14178242/15437593/44ef584a-1ec8-11e6-9eca-d06bd11e5bcf.jpg)

**Comment by cchamplin** [comment]
I'm going to close this for now. If you are still experiencing this issue please reopen with your xdebug and php-debug configuration.
