### ISSUE TITLE
Allow hiding some panels (Stack, Context, Watchpoints, Breakpoints)

### ISSUE THREAD

**Issue by ricpelo** [gwomacks/php-debug#165]
This is a great tool. Unfortunately, my tiny screen gives me little width space.

For instance, the Context panel is very useful for me; however, I never use watchpoints. With the actual layer, the Context panel has very little width so I need to continously scroll it left & right in order to see all the variables and their values. Hiding the Watchpoints panel will bring me more width space for the Context panel.

Ability to hide some of the information panels (Stack, Context, Watchpoints, Breakpoints) could be great.

Thanks in advance!

**Comment by ricpelo** [comment]
The ability to stack the panels vertically (instead of the horizontal current layout) could be great, too.

**Comment by nahuelhds** [comment]
+1

**Comment by cchamplin** [comment]
This should be partially addressed in f04b55b and should land in v0.2.4. That commit adds the ability to hide panels, letting the others fill the space.
