### ISSUE TITLE
Feature Request: Console

### ISSUE THREAD

**Issue by AlexMax** [gwomacks/php-debug#169]
Some other Xdebug implementations, such as Codebug, have a nice "Console" that allows me to execute arbitrary code within the context of a running function or class method.  For example, I could execute `$this->foobar()` and get a glimpse of what that method returns.  Something like [this](https://i.imgur.com/c6ZkBLF.png).

Is it possible?

**Comment by belaustegui** [comment]
+1 here. Would be a wonderful feature.

**Comment by cchamplin** [comment]
Agreed, will see what I can come up with for next release.

**Comment by maaarghk** [comment]
As a temporary workaround I use the watchpoints screen for this. Just remember to delete the watchpoint when you're done or it'll run in another context and throw an error. Not ideal though - console would still be great.

**Comment by cchamplin** [comment]
This has been addressed in d98f794 and should land in v0.2.4
