### ISSUE TITLE
Wrong local file opened when debugging remote using multiple PathMap values.

### ISSUE THREAD

**Issue by acrosman** [gwomacks/php-debug#174]
I have two vagrant boxes that I move back and forth between that have similar, but critically different, setups. The host OS is MacOS and the remotes are both Ubuntu 14.04. So not surprisingly they both have the same remote value for the file path in the Path map: `/var/www/vhosts`, but the local values are different:  `/Users/[user]/Documents/Collection1/sites` and `/Users/[user]/Documents/Collection2/sites`.

```
"php-debug":
  PathMaps: [
    "/var/www/vhosts/;/Users/myUser/Documents/Collection1/sites/"
    "/var/www/vhosts/;/Users/myUser/Documents/Collection2/sites/"
  ]
  ServerPort: 9000
```
php-debug correctly pauses execution at the right spot in both cases. 
For sites in Collection1 it works correctly.
But for sites in Collection2 it attempts to open the file using the Collection2 path.

So when running a site from Collection2 it will break where it should and then open `/Users/myUser/Documents/Collection1/sites/myfile.php` instead of `Users/myUser/Documents/Collection2/sites/myfile.php`.  Usually this doesn't exist and therefore it appears to be a blank file.

Is there a solution to this (like adding some kind of hint to the mapping array to help guess where to look), or does this end up as a "don't do that" situation?

**Comment by cchamplin** [comment]
Ya I don't think we have a straight forward way to support this use case. I'm going to close this for now, you can reopen as a feature request if it's important to you.
