### ISSUE TITLE
FR: information columns as panels

### ISSUE THREAD

**Issue by nahuelhds** [gwomacks/php-debug#175]
This is a feature request.

The current columns for Stack, Context, Watchpoints and Breakpoints maybe could be distributed as Tabs (something like this in [Bootstrap](http://getbootstrap.com/components/#nav-tabs)) or Pills (also in [Bootstrap like this](http://getbootstrap.com/components/#nav-pills)).

In that way every panels would use the total width of the area and not just a 25%. Some strings are very long and the current distribution makes sometimes difficult to read the entire data in a proper way.

Anyway, the plugin is EXCELLENT. Thanks for such a great job.

If you need help with this (if you are willing to apply this feature), let me know. I'm glad to help with this by doing a pull request.

Regards

**Comment by cchamplin** [comment]
I do agree that the stack panel leaves something to be desired. I am uncomfortable switching to tabs as a solution by default though as it makes it difficult to see the entire context of a breakpoint. Possibly can get this added as a configurable option.

**Comment by cchamplin** [comment]
This should be partially addressed in f04b55b and should land in v0.2.4. That commit adds the ability to hide panels, letting the others fill the space.

**Comment by nahuelhds** [comment]
Totally +1 for [f04b55b ](https://github.com/gwomacks/php-debug/commit/f04b55bfabb5d757cf17ba376d3c5318cfcfe925). Cannot wait for 0.2.4 then!
