### ISSUE TITLE
Remote path not applied in chroot

### ISSUE THREAD

**Issue by tino415** [gwomacks/php-debug#176]
I have lamp in chroot-ed environment and mi config looks like:

``` coffescript
"php-debug":
  {
    ServerPort: 9000
    PathMaps: [
      "remotepath;localpath"
      "/home/martin/Projects;/mnt/old/home/martin/Projects"
    ]
  }
```

but PathMaps did not get applied.

**Comment by cchamplin** [comment]
Can you provide any additional information on what you mean by PathMaps did not get applied. Are you not getting breaks from xdebug?

**Comment by tino415** [comment]
I get breaks but editor still triing to open reported files on local machine, not in chroot environment

**Comment by QwertyZW** [comment]
I don't understand the issue./mnt/old/home/martin/Projects should be a local mirror of the remote  /home/martin/Projects ; so whether the package trys open the remote files (it can but it doesn't as of this writing) it should not matter

**Comment by tino415** [comment]
I debug remote file `/home/martin/Projects/test.php` and when it stops on break point it tries to open file `/home/martin/Projects/test.php` instead of mapped file `/mnt/devel/home/martin/Projects/test.php` according to PathMaps. On local machine `/home/martin/Projects/test.php` does not exists.

**Comment by QwertyZW** [comment]
can you upload your config.cson? (File -> Config...)

**Comment by tino415** [comment]
Maybe tomorow, synce I had this problem I was changing OS and was not triing to make it work
