### ISSUE TITLE
Breaking on @ sign

### ISSUE THREAD

**Issue by surfer190** [gwomacks/php-debug#178]
It is breaking on the suppress error `@` sign

**Comment by istian** [comment]
+1 on this issue... hope this one get fix..  it's tedious clicking Continue until it gets to the breakpoint you want..  or is there a setting to avoid this?

**Comment by cchamplin** [comment]
You should be able to adjust this by unchecking break on php exceptions/warnings/notices etc. Closing this, feel free to reopen if you need additional support.
