### ISSUE TITLE
breaking randomly

### ISSUE THREAD

**Issue by mihaibrehar** [gwomacks/php-debug#179]
I've got a very strange behaviour in Ubuntu 14.04 and Atom 1.9.9 (but also tested with older versions).
Xdebug version is 2.2.3

The debugger is breaking randomly. I press on "Continue" and it just jumps to another random place.
Sometimes it jumps to the next line.

I've cleared all breakpoints and then I've added one single breakpoint, but I can not reach it.

Very strange stuff. What can be the cause?

**Comment by cchamplin** [comment]
You should be able to adjust this by unchecking break on php exceptions/warnings/notices etc. Closing this, feel free to reopen if you need additional support.
