### ISSUE TITLE
Breakpoints not working correctly

### ISSUE THREAD

**Issue by devarni** [gwomacks/php-debug#180]
Debugger stops at the first included PHP file and not at the breakpoint. For me in the Wordpress installation it's in the first included file from the main config.
This is a bug.

It's a local running server so it doesn't need path mapping. It works also with other tools (Brackets, Visual Studio Code, PHPStorm etc).
Using the "debug_break()" function is also not working. The debug session starts always at the first php file.

Btw. some IDEs having the option "Don't break at the first line" and it seems that other implementations using Xdebug having this implemented as the default? Maybe it needs some small changes so the debugger will not stop at the first line?

**Comment by cchamplin** [comment]
You should be able to adjust this by unchecking break on php exceptions/warnings/notices etc. Closing this, feel free to reopen if you need additional support.
