### ISSUE TITLE
it stop at breakpoints.but not highlighted.can't step in....

### ISSUE THREAD

**Issue by okamok** [gwomacks/php-debug#181]
hi everybody.i'm MASA.
i tried to PHP debug with ATOM & xdebug(php-debug).
but it don't goes well.

i did follow things.

**1.install xdebug.**
https://xdebug.org/wizard.php

**2.add this to my php.ini**

> xdebug.remote_enable=1
> xdebug.remote_host=127.0.0.1
> xdebug.remote_port=9000
> xdebug.remote_handler=dbgp
> xdebug.remote_mode=req
> xdebug.remote_autostart=true

after add this,i could checked xdebug on phpinfo().

**3.php-debug install on ATOM**

**4.i'd like to debug on my local.not remote.**
so i didn't set PathMaps.

**5.set breakpoint on ATOM and kick program on browser(google chrome).**

**6.it occurred to me how weird thing.**
row set breakpoint didn't be highlighted.
but stack was working.
button(continue,step over,and so on...) became active.
once i click "step over",stack was working.

![2f94923af2889865b512c0a65b0ca03d41091d2f_1_690x371](https://cloud.githubusercontent.com/assets/1357393/18304369/0d6df47a-751d-11e6-9e28-86542e0da5d1.JPG)
this image show it stop on row 109.but not highlighted.
if i click "step in".stack was working,but not change screen.not chase program.
i tried other browser(firefox,IE).
but problem never went away...

any help would be appreciated!
best regard,

**Comment by cchamplin** [comment]
Should be fixed in v0.3.0
