### ISSUE TITLE
Just wanted to leave this here...

### ISSUE THREAD

**Issue by Gert-dev** [gwomacks/php-debug#183]
Hello

I noticed that another user developing a GDB debugger front-end for Atom has split off his debugger controls for reuse as a service by other packages. I don't know if this is sufficient for php-debug, but it may be interesting nonetheless. I'll just leave the link to it here: https://github.com/31i73/atom-dbg

If it is viable it may take some of the load off this package as only the provider part plugging into xdebug or php-dbg would remains.

Feel free to close this whenever you like as it's not an actual bug and thanks for your work!

**Comment by cchamplin** [comment]
Thanks, will keep my eye on this. At the moment it looks like the project lacks some of the functionality we  need (watchpoints).

**Comment by Gert-dev** [comment]
Sorry to bump this again, but I didn't want to create a new issue to bother you again. Another interesting package to keep an eye on might be [bottom-dock](https://github.com/benjaminRomano/bottom-dock/) package. This would allow you to get a dock for free, where you only have to provide the view in it. The advantage is that it allows users to switch between tabs of various packages via a single dock rather than all of these packages having their own way of creating a dock.

Keep up the nice work! :-)
