### ISSUE TITLE
xdebug always stop on first line of some files.

### ISSUE THREAD

**Issue by rodrigotechera** [gwomacks/php-debug#184]
I have just installed php-debug and is working but it is stopping on the first line of a bunch of files which I haven't added a break point.

Is there a way to disable this? May I be missing any configuration?

Thanks

**Comment by istian** [comment]
@rodrigotechera , you try unchecking all exception in the settings panel for php-debug.

**Comment by rodrigotechera** [comment]
That worked, thanks for your answer!
