### ISSUE TITLE
Red line: what does it mean?

### ISSUE THREAD

**Issue by rzelnik** [gwomacks/php-debug#185]
If the debugging process stops on a line that is highlighted dark red, how can I find out, what kind of error or warning causes the break?

**Comment by cchamplin** [comment]
Ideally we need a console for exception messages, along with some kind of contextual message for the associated code points. I'll see what I can come up with in the coming weeks.

**Comment by cchamplin** [comment]
This has been addressed in d98f794 and should land in v0.2.4
