### ISSUE TITLE
Changes required for upcoming CoffeeScript upgrade

### ISSUE THREAD

**Issue by maxbrunsfeld** [gwomacks/php-debug#186]
Hi! Thanks for maintaining the php-debug package!

In Atom v1.12, we are going to [upgrade CoffeeScript](https://github.com/atom/atom/pull/12780) to the latest version. This upgrade entails one potentially breaking change to the language:

> Changed strategy for the generation of internal compiler variable names. Note that this means that @example function parameters are no longer available as naked example variables within the function body.

We think your package may be affected by this upgrade, in the following places:
- The `gutter` variable [here](https://github.com/gwomacks/php-debug/tree/master/lib/models/breakpoint-marker.coffee#L8)

These findings are based on linting packages with `coffeescope`. We could be wrong about some of them. When we release v1.12 beta, please test your package against it to make sure that it works. Let me know if you have any further questions; I will be happy to help!

**Comment by cchamplin** [comment]
Will evaluate a fix for this if necessary.

**Comment by sbrl** [comment]
Yep, this is an issue now. See #194.

**Comment by phearlez** [comment]
With #194 closed this presumably can be closed as well.
