### ISSUE TITLE
Backspace no longer works when typing Watchpoint

### ISSUE THREAD

**Issue by JasonTheAdams** [gwomacks/php-debug#198]
Hello! After updating to 0.2.4 I'm not longer able to backspace when typing in a Watchpoint. No error or anything. It simply doesn't do anything.

**Comment by joestock** [comment]
I am experiencing this same issue.  Also, arrow keys, delete button don't seem to work in the Watchpoints field either.  The work around is to right click and use the context menu which seems to be operational.  I noticed that the home and end buttons work.

**Comment by shemayas** [comment]
Same issue,
Also can't cut and past with keyboard shortcuts.

**Comment by iglad** [comment]
I have same issue, when type some mistake character, don't work delete, backspace, and arrow keys left and right. I press Enter and delete mistake typing.

**Comment by rainmaker666** [comment]
Facing the same problem. I have tried to disable all other plugins but it doesn't help.

**Comment by cchamplin** [comment]
This should be fixed in 0.2.5.
