### ISSUE TITLE
How to reopen closed Watchpoint section?

### ISSUE THREAD

**Issue by JasonTheAdams** [gwomacks/php-debug#199]
I clicked the "x" in the Watchpoint section thinking it may be a nice, new way of removing all the watchpoints. Instead it removed the section. I then couldn't figure out how to get it back, resorting to closing Atom entirely and reopening it. I'm glad that worked!

**Comment by cchamplin** [comment]
There should be a "Restore Panels" button that restores them.

**Comment by JasonTheAdams** [comment]
I figured that was probably it, but when I hover my mouse over that button I get the cursor with a circle and a line through it -- indicating verboten. Ignoring that and clicking doesn't do anything, either.

**Comment by kenorb** [comment]
Same here, closed panels by accident, now _Restore Panels_ is grayed out and it's not clickable.

**Comment by cchamplin** [comment]
This will be fixed in the 0.2.5 release.
