### ISSUE TITLE
Debug section collapsing

### ISSUE THREAD

**Issue by oniramarf** [gwomacks/php-debug#200]
While using the php-debug package I have encountered the following issue: after my debug session is completed, the debug section collapses.

The size of the available windows reduces slowly until it is collapsed to minimum and it is impossible to use it.

After restarting, the debug panel is back to normal, but it is really frustating to close and reopen the editor after each debugging session.

Could you help me solve this issue?

**Comment by oniramarf** [comment]
I also add that I am using the debug console on right side insthead of using the default bottom position.

**Comment by nikita-kiryanov** [comment]
I also have the same problem (also using the debug console on right side).

**Comment by joestock** [comment]
I ran into a similar issue with this but I keep mine at the bottom. However, if you go into your config  file, under "php-debug":

reset currentPanelHeight: "50px" or something other than zero. Each time you drag and resize the panel it changes the currentPanelHeight setting. Not sure but hope this helps.

**Comment by cchamplin** [comment]
I have not been able to reproduce this. Do can you provide your config?

**Comment by cchamplin** [comment]
Likely fixed as part of rewrite for v0.3.0
