### ISSUE TITLE
Long strings are truncated

### ISSUE THREAD

**Issue by ghost** [gwomacks/php-debug#201]
Hello

The latest update introduced more polishing to the package, which is great! A small item I noticed is that long strings in the debug panel (where the values of variables are shown) are truncated. This is understandable, seeing as they are too long to display. However, something like a tooltip on hover or a way to "edit" them so their value can be copy-pasted out would be neat.

Thanks in advance and keep up the good work! This package has come a long way since its initial (somewhat buggy) release.

**Comment by cchamplin** [comment]
I am not seeing the same thing, typically the window size of the variables should grow to accommodate longer strings and you should be able to scroll right/left to see them. Can you provide a screen shot.
