### ISSUE TITLE
Trailing slashes lead to weird bugs

### ISSUE THREAD

**Issue by QwertyZW** [gwomacks/php-debug#203]
Trailing slashes in the local/remote config lead to undefined behavior.

See this fix for details https://github.com/gwomacks/php-debug/pull/191. This fix only gets rid of the trailing slashes, it wouldn't stop the undefined behavior should anything else lead to it.

Still needs to be done: Fix bugs caused by trailing slashes.

**Comment by cchamplin** [comment]
Should be fixed in v0.3.0
