### ISSUE TITLE
xdebug.remote_autostart= On

### ISSUE THREAD

**Issue by CallMarl** [gwomacks/php-debug#205]
Hey,

I prefer to use xdebug.remote_autostart= On as xdebug.remote_autostart = true

the rule xdebug.remote_autostart = true wasn't working with me. The bug was: nothing appends on my php-debug. if you want to check if you have the same problem, you must create this request on your url: 
"my-url.dev?XDEBUG_SESSION_START=vscode". If after that your php debug works, you must change the value of xdebug.remote_autostart at On.

**Comment by devgiu** [comment]
Don't works for me. I get on PHP-debug panel, Connected, but don't stops on breakpoints and nothing more. I forced an exception with $mi = anonexistentfunction(); and don't stops either :(

**Comment by cchamplin** [comment]
I believe this is out of scope for this project
