### ISSUE TITLE
There is a conflict between php-debug and php-cs-fixer on macOS

### ISSUE THREAD

**Issue by oknixus** [gwomacks/php-debug#207]
There is an orginal php on macOS, but for installing php-debug, I had to installed another php.
The path of orginal php is /usr/bin/php, and the new installed one, its path is /usr/local/bin/php.
If I rename the new one, the php-debug doesn't work.
If I do nothing , the dear php-cs-fixer will show me something in the below pic :
![01271ef2-d4b9-11e6-8f0e-911aac6cf195](https://cloud.githubusercontent.com/assets/4592706/21738249/13cdc944-d4bd-11e6-8bb9-ac78d234a37c.png)

I want to do something with the orginal php, but I have not a permitted:
![5264c2aa-d4ba-11e6-9568-dde81503cb20](https://cloud.githubusercontent.com/assets/4592706/21738251/1a126f1c-d4bd-11e6-83da-0592e92c43f3.png)

Could you help me with this ?

**Comment by cchamplin** [comment]
I believe this is out of scope for this project
