### ISSUE TITLE
crash debug with atom-autocomplete-php

### ISSUE THREAD

**Issue by felocru** [gwomacks/php-debug#208]
Hello, I want to make one consult.
When I run the debugger without the atom-autocomplete-php it works wonderfully.
But when I run with him. It crashes, without showing me messages.
I have tested with other packages and I do not have this problem.
Can someone guide me?
Thank you!

**Comment by matheust3** [comment]
I'm having the same problem...

**Comment by cchamplin** [comment]
Possibly fixed in v0.3.0. If not reopen.
