### ISSUE TITLE
Path Map Settings in README is misleading

### ISSUE THREAD

**Issue by matthewpoer** [gwomacks/php-debug#216]
I find the Settings information to be misleading. 

The README.md specifies the `config.cson` should contain the following:
~~~
"php-debug":
  {
    ServerPort: 9000
    PathMaps: [
      "remotepath;localpath"
      "/base/path/on/remote/system;C:\\base\\path\\on\\local\\system"
    ]
  }
~~~

What is actually generated by the settings dialog is this:
~~~
"*":
  "php-debug":
    PathMaps: [
      "/srv/repo/www;/Users/matthewpoer/PhpstormProjects/sugar/repo/www"
    ]
~~~

One could also just include a screenshot of the Settings dialog where you can easily specify a CSV set of PathMap options.

**Comment by cchamplin** [comment]
Should be fixed in v0.3.0
