### ISSUE TITLE
XDebug doesn't halt on breakpoints

### ISSUE THREAD

**Issue by humblecoder** [gwomacks/php-debug#218]
I'm using php-debug 0.2.4 with Atom 1.15.0 x64 on macOS 10.12.3.  I'm connecting to PHP7-fpm on a Vagrant instance.  My current config is as follows:

`
zend_extension=xdebug.so

xdebug.remote_enable=1
xdebug.remote_connect_back=1 
xdebug.remote_port=9000
xdebug.remote_handler=dbgp
xdebug.remote_mode=req
xdebug.remote_autostart=true
xdebug.show_local_vars=1
`

Both MacGDBp and CodeBug perform correctly.  They halt at each breakpoint.  Atom, however, when the page refreshes, says "connecting" then simply returns to "Listening on port 9000" with no stopping or output otherwise.

**Comment by austingray** [comment]
@humblecoder FWIW, I was experiencing the same issue. After playing with my settings, I got it to work.

xdebug.ini
```
 zend_extension=xdebug.so
 xdebug.remote_enable=1
 xdebug.remote_port=9000
 xdebug.remote_autostart=1
```

config.cson
```
"*":
  [...other settings]
  "php-debug":
    PathMaps: [
      "project/path/in/vagrant;project/path/on/local"
    ]
    ServerPort: 9000
    currentPanelHeight: "603px"
    currentPanelMode: "bottom"
```

I also removed my IDE key from the xdebug-helper, the chrome extension I'm using: https://chrome.google.com/webstore/detail/xdebug-helper/eadndfjplgieldjbigjakmdgkmoaaaoc

**Comment by TobyMudito** [comment]
@humblecoder Try to change xdebug.remote_autostart to false, as https://github.com/gwomacks/php-debug informs. Maybe it fixes your problem.

**Comment by cchamplin** [comment]
This is likely a pathmaps issue resulting in the breakpoint never being set. Can you confirm your pathmaps are correct?
