### ISSUE TITLE
No longer stops on breakpoints...

### ISSUE THREAD

**Issue by mattbryson** [gwomacks/php-debug#226]
Hi, this plugin has been working brilliantly for me until recently.

I'm not sure what the change is, Atom has updated, but our dev env has not changed, that config is exactly the same.

The PHP execution does halt, and the debugger says "connected", but all of the "step in", "step over" controls are disabled, and it doesn't stop on any break points.

if I close the debugger then execution carries on - so it is connecting, its just not going to a break point or letting me control it....

Atom : 1.17.2

XDEBUG config
zend_extension=/usr/lib64/php/modules/xdebug.so
xdebug.remote_enable=1
xdebug.remote_host=192.168.10.1
xdebug.remote_autostart=1

**Comment by cchamplin** [comment]
Can you check if you are still having issues in 0.2.6?
