### ISSUE TITLE
Clicking on PHP Debug panel clears the debug session

### ISSUE THREAD

**Issue by kenorb** [gwomacks/php-debug#230]
While debugging (xdebug), when I click on _PHP Debug_ (next to _PHP Console_) to hide the panel and show again, the debugging session is lost (e.g. Stack and Context is empty).

**Comment by cchamplin** [comment]
Closing the debugging panel ends all debugging sessions/connects. This is intended. The closest thing to hiding while keeping your session would be to drag the panel to the bottom making it as small as possible.
