### ISSUE TITLE
Can't remove Watchpoints item

### ISSUE THREAD

**Issue by kenorb** [gwomacks/php-debug#231]
I've added `$dst` variable, but I can't remove it. Clicking on the X button which is on top of the text, but still doesn't work. The debugger is not activate at that time.

<img width="347" alt="screen shot 2017-07-01 at 17 15 43" src="https://user-images.githubusercontent.com/266306/27763726-19808842-5e81-11e7-9e77-487767914299.png">

Although the item disappears on the next run.

**Comment by cchamplin** [comment]
Should be fixed in v0.3.0
