### ISSUE TITLE
Code stops each time at @mkdir($dst) line

### ISSUE THREAD

**Issue by kenorb** [gwomacks/php-debug#232]
Each time when I run my Behat tests, the code stops at:

    @mkdir($dst);

line despite I don't have any breakpoint at this line. Why this happens and how to disable this?

Here are these lines from BehatHtmlFormatterPlugin:

- [copyAssets()](https://github.com/dutchiexl/BehatHtmlFormatterPlugin/blob/master/src/Printer/FileOutputPrinter.php#L207)
- [recurse_copy()](https://github.com/dutchiexl/BehatHtmlFormatterPlugin/blob/master/src/Printer/FileOutputPrinter.php#L219)

**Comment by cchamplin** [comment]
This is likely due to your exception breaking settings. Can you try adjusting those in the atom settings and let me know if it resolves the issue?

**Comment by kenorb** [comment]
I think it is. I believe disabling `xdebug.show_exception_trace` helped, but I won't be able to verify the previous setup.
