### ISSUE TITLE
Ability to resize debug panels

### ISSUE THREAD

**Issue by kenorb** [gwomacks/php-debug#234]
Currently there are 4 panels (Stack, Context, Watchpoints and Breakpoints). Sometimes the text is cut off and I understand that I can scroll to the right to see the text. But is it also possible to make them resizable?

![screen shot 2017-07-12 at 14 53 23](https://user-images.githubusercontent.com/266306/28121150-1fb82f46-6712-11e7-969b-7710418e8a9b.png)
![screen shot 2017-07-12 at 14 54 37](https://user-images.githubusercontent.com/266306/28121154-231006e6-6712-11e7-85b5-845f56c251f0.png)

So Stack can be wider than Context, or opposite?

**Comment by cchamplin** [comment]
The standard approach for this would be the close the other panels and let the remaining ones fill in the space. Does this meet your needs?

**Comment by kenorb** [comment]
It is some workaround, but I think all panels are useful to have them open, but some just have longer texts than the other, so having them in fixed equal size isn't always great.

I think ability to resize them as you like (similar with everything else in Atom) would be a great feature.

**Comment by finswimmer** [comment]
Hello,

is it possible that the debug panel can also be open in it's own window (maybe in a future release)? Than there would be enough space for all the information, especially if I'm working with two displays.

fin swimmer

**Comment by cchamplin** [comment]
Should be fixed in v0.3.0
