### ISSUE TITLE
Always getting "error evaluating code" in xdebug php console

### ISSUE THREAD

**Issue by megusta420** [gwomacks/php-debug#243]
Hi!
Thanks for the plugin but got stuck with evaluating php code in xdebug console for atom.
Tried a lot of variants like "<?php echo 1; ?>" or "echo 1;" and even "echo 1" but all time getting error "error evaluating code". 

![image 3](https://user-images.githubusercontent.com/28196153/29463378-21e07aa8-843b-11e7-82f4-e6b9f6bfc25e.png)

**Comment by cchamplin** [comment]
Can you try just evaluating something like "1==1"
