### ISSUE TITLE
Make debug a tab rather than a whole panel

### ISSUE THREAD

**Issue by nsrosenqvist** [gwomacks/php-debug#247]
Rather than using the newer tabs that can be attached to the lower or right portion of the editor it currently opens it's own tab that takes up significantly more space if one of the side panels are open (see screenshot). I would much prefer if it was added as a tab along with the outline view.

![screenshot from 2017-09-30 13-08-35](https://user-images.githubusercontent.com/1303475/31040194-bb502be0-a5e0-11e7-8804-3734237ac63c.png)

**Comment by cchamplin** [comment]
Should be fixed in v0.3.0
