### ISSUE TITLE
Opens multiple files at random locations instead of going to breakpoint

### ISSUE THREAD

**Issue by mrthebob** [gwomacks/php-debug#258]
When a connection is made, the debugger starts in a random place - not at any breakpoint I set - and then it proceeds to go through a series of files, opening each one as it goes. EVENTUALLY (I think), it will get to my breakpoint, but I kind of think it should just go straight there...

~ ᐅ atom --version
Atom    : 1.22.0
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

php-debug version 0.2.5

**Comment by cchamplin** [comment]
This is likely because your pathmaps are not correct. They have been changed in 0.3.0 to be easier to manage. I'm going to close this for now, please reopen if it's still an issue after upgrading.
