### ISSUE TITLE
Error debugging PHP running 'Listen for XDebug'

### ISSUE THREAD

**Issue by juanqui66** [gwomacks/php-debug#259]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|0.23.0
ionic3-vs-ionView-snippets|dan|1.0.1
githistory|don|0.2.3
php-debug|fel|1.12.0
vscode-git-tags|how|1.1.2
cordova-tools|vsm|1.3.1

---

Steps to Reproduce:

1. Press in 'Listen for XDebug'.
2. Appears: '_El proceso de adaptación del depurador finalizó inesperadamente_' twice.

Until now, the PHP debugger worked correctly. Since a few minutes I see this error (in Spanish) without having changed any configuration, simply restarting VS Code.

My PHP server in XAMPP and my version of XDebug is php_xdebug-2.5.4-7.0-vc14.dll.

Any ideas?

My VS Code configuration:

{
     // Señala al ejecutable PHP.
  "php.validate.executablePath": "D:/XAMPP/php/php.exe",
  "editor.tabSize": 2,
  "window.zoomLevel": 0,
  "php.validate.enable": true
  
}

My launch.json:

{
  // Utilizar IntelliSense para aprender acerca de los posibles atributos.
  // Mantenga el puntero para ver las descripciones de los existentes atributos 
  // Para más información, visite: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Listen for XDebug",
      "type": "php",
      "request": "launch",
      "port": 9000
    },
    {
      "name": "Launch currently open script",
      "type": "php",
      "request": "launch",
      "program": "${file}",
      "cwd": "${fileDirname}",
      "port": 9000
    }
  ]
}

Thanks in advance.

**Comment by StAmourD** [comment]
@juanqui66 The VS Code addin is over here:

https://github.com/felixfbecker/vscode-php-debug

This project is for Atom :wink:

**Comment by juanqui66** [comment]
Thanks @StAmourD for the contribution (I'll write it down because I also use Atom sometimes). The problem just as it came, he left after 3 days, without doing anything special to solve it.

Thank you anyway.
