### ISSUE TITLE
PHP-debuger don't work .. (sorry for not looking good for view.)

### ISSUE THREAD

**Issue by SangYunLeee** [gwomacks/php-debug#263]
I followed  this instoll  URL (https://atom.io/packages/php-debug)

but atom php-debuger dont work.. 
 when i chick 'continue' or etc in bellow picture,  mouse icon become 
![dd](https://user-images.githubusercontent.com/35091494/34551774-1dcff35c-f160-11e7-8e87-26400f0b3638.jpg)

<img width="188" alt="2" src="https://user-images.githubusercontent.com/35091494/34551788-380442fa-f160-11e7-84c3-735f29c76cb8.PNG">

is there anyone who help me... 
i checked phpinfo();. and xdebug is instrolled.

bellow is my condition. 
<img width="348" alt="3" src="https://user-images.githubusercontent.com/35091494/34551829-7a6d159a-f160-11e7-9b35-cc65da0b73fc.PNG">
<img width="243" alt="4" src="https://user-images.githubusercontent.com/35091494/34551830-7a9bd772-f160-11e7-823e-de926a6b07af.PNG">
<img width="495" alt="default" src="https://user-images.githubusercontent.com/35091494/34551832-7ac97ca4-f160-11e7-8353-c238b61ec461.PNG">

**Comment by arorasuneet** [comment]
I am also unable to use php-debug despite all the configurations mentioned in the documentation.
OS:  Windows 8
Atom editor:  ver 1.24.0 ia32
php-debug package:  php-debug 0.2.6
Xamp: 7.2.2 / PHP 7.2.2

Installed the package and the Chrome extension as well. But it is not working despite all the configuration settings in PHP.ini and config.cson I could find.  Any help is highly appreciated. Thanks!

**Comment by cchamplin** [comment]
I'm guessing a connection is never getting started. This should be clearer and work my consistently in 0.3.0. I'm going to close this for now, if it's still an issue please reopen.
