### ISSUE TITLE
UI Freezes when breakpoint is hit

### ISSUE THREAD

**Issue by bkmeneguello** [gwomacks/php-debug#266]
Whenever the debugger stops at some breakpoint or any watch is added the entire UI freezes until the variables are evaluated.
It seems to be related to context evaluation.
In my case, it's worst because I'm debugging a slow remote server.
It should happen in background, disabling debug actions while the process happens and enabling them when the response arrives.
If possible, allow to continue while waiting for response and update partial responses (not wait for all context evaluation to update the view)

**Comment by jarrettj** [comment]
Hi,

Good day.

Same issue here. This happens when debugging local source as well. It just hangs. 

Regards.
JJ

**Comment by cchamplin** [comment]
Should be fixed in v0.3.0. If not please reopen.
