### ISSUE TITLE
Add ability to toggle auto-breaks

### ISSUE THREAD

**Issue by JasonTheAdams** [gwomacks/php-debug#267]
Currently if there is an error somewhere in the code it automatically stops on that line with the red highlight. Sometimes I want to debug something but some other plugin I have no control over is throwing warnings. I know they're there but they're minor and can be ignored.

It would be great to be able to toggle the auto-breaks so it only stops on explicit breaks that the user sets.

Thanks! Invaluable tool!

**Comment by cchamplin** [comment]
Should be fixed in v0.3.0
