### ISSUE TITLE
SOME breakpoints not showing any variables and causing Socket Error

### ISSUE THREAD

**Issue by iainhouston** [gwomacks/php-debug#269]
Similar [to this issue here](https://github.com/gwomacks/php-debug/issues/268) with Atom php-debug 0.2.6. (although I have it working on PHPStorm so guess Xdebug setup is OK).    
With Atom `php-debug` I get a socket error ... See screenshot below.
`php-debug` works fine at the point when execution hits Drupal's `index.php` and stepping through some PHP statements thereafter but as things progress towards MYTHEME.theme PHP program statements, `php-debug` will halt at the breakpoint but will show no variables and the vagrant Apache server will timeout? giving a *Bad Gateway*
<img width="552" alt="screen shot 2018-03-11 at 11 22 31" src="https://user-images.githubusercontent.com/537596/37252772-313152fe-251f-11e8-9e87-17fef753ecd5.png">

First `php-debug` stops at `index.php` and shows variables.
<img width="951" alt="screen shot 2018-03-11 at 11 21 37" src="https://user-images.githubusercontent.com/537596/37252764-f5723e18-251e-11e8-8ab5-592dbd15858d.png">

Then it hits MYTHEME.theme (which is in a directory subordinate to the path mapping that allowed `index.php` to work. And yes, the statement was green moments before I took the snapshot but the variables were not shown - per the screenshot)
<img width="938" alt="screen shot 2018-03-11 at 11 22 00" src="https://user-images.githubusercontent.com/537596/37252771-271a0658-251f-11e8-9543-50a3de381ea9.png">

**Comment by cchamplin** [comment]
I'm hoping this was fixed in 0.3.0. Can you update and retest?

**Comment by iainhouston** [comment]
Tried again with 0.3.3  - still no joy

-  stops at breakpoint (in Drupal's `index.php`) and highlights line green  
-  cannot move on from breakpoint
   -  Debug controls don't do anything
- No variables are shown under the *Context* column

<img width="1069" alt="screen shot 2018-05-07 at 00 02 28" src="https://user-images.githubusercontent.com/537596/39678787-eec3163a-518a-11e8-94fc-d7162bb42b8d.png">

**Comment by iainhouston** [comment]
Joy! 0.3.4 doing the business! Thanks.
