### ISSUE TITLE
debug interface gets shrinked on every loaded PHP page

### ISSUE THREAD

**Issue by fernandopsilveira** [gwomacks/php-debug#270]
![shrinking](https://user-images.githubusercontent.com/1727562/38420160-42742c1c-3979-11e8-9762-a61320db3b3b.gif)

**Comment by fernandopsilveira** [comment]
that happens until the point you can't see anything anymore

**Comment by fernandopsilveira** [comment]
that happens until the point you can't see anything anymore unless you restart Atom

**Comment by cchamplin** [comment]
Should be fixed in v0.3.0
