### ISSUE TITLE
Keeps asking to install ide-php

### ISSUE THREAD

**Issue by tominventisbe** [gwomacks/php-debug#276]
I've said `Never` to the question to install `ide-php` package, and I even see `ide-php` in the package settings in the disabled prompt list, but php-debug does not seem to take no for an answer and still keeps asking me to install `ide-php` on every startup :smile: .

**Comment by cchamplin** [comment]
Should be fixed in 966d988 which should land in v0.3.1 later today. Thanks

**Comment by cchamplin** [comment]
Should be fixed in v0.3.1. Please let me know if you experience continued issues around this.

**Comment by tominventisbe** [comment]
Seems to be fixed, thanks!
