### ISSUE TITLE
Can't make it works after the update

### ISSUE THREAD

**Issue by Sikito** [gwomacks/php-debug#281]
It was working juste fine until de 0.31 update.
Here what i did : 

+  I just installed atom-debug-ui.  Does it work without the 2 other packages?

+ Here my php.ini file : 
zend_extension="c:/wamp64/bin/php/php7.2.4/zend_ext/php_xdebug-2.6.0-7.2-vc15-x86_64.dll"
xdebug.remote_enable=1
 xdebug.remote_host=127.0.0.1
 xdebug.remote_connect_back=1    # Not safe for production servers
 xdebug.remote_port=9000
 xdebug.remote_handler=dbgp
 xdebug.remote_mode=req
 xdebug.remote_autostart=false      => because i have firefox xdebug module

 
+ Here is my config file : 

  "php-debug":
    currentPanelMode: "bottom"
    display:
      views: {}
    exceptions: {}
    noPackageInstallPrompt: [
      "atom-debug-ui"
      "atom-ide-ui"
      "ide-php"
    ]
    server:
      protocolDebugging: true
      serverAddress: "127.0.0.1"
    showWelcome: false
    xdebug:
      pathMaps: "C:\\wamp64\\bin\\php\\php7.2.4\\zend_ext\\php_xdebug-2.6.0-7.2-vc15-x86_64.dll"
  welcome:
    showOnStartup: false

What pathmaps? the path to xdebug.dll or something else ?

**Comment by cchamplin** [comment]
Can you update to 0.3.3 which dropped this morning?

**Comment by Sikito** [comment]
Thank you, it's working now
