### ISSUE TITLE
php-debug got updated to 0.3.3 on Atom and now it doesn't work

### ISSUE THREAD

**Issue by jvlobo** [gwomacks/php-debug#284]
My php-debug package was working perfectly, but now it got updated to version 0.3.3 and it doesn't work at all. I'm running Atom 1.26.1 on OS X High Sierra 10.13.4 (17E199)

When updated it required a package or theme or something, so I installed it, now I set a breakpoint and  it asks me to set a path map? I don't remember having any path map configuration nor I know which one to set now. Anyways I try setting something, then it keeps asking me to add a path map... the PHP Debug block at the bottom gets closed... a disaster... I don't know what to do.

Hope you guys can help or fix it.

Thanks!

**Comment by cchamplin** [comment]
I would suggest trying to remove all of the PHP-Debug settings from config.cson and trying again, it's possible the setting got corrupted resulting in it prompting every time. Let me know.

**Comment by jvlobo** [comment]
I've updated to v0.3.4 and it seems like everything is working fine again.

Thanks!!
