### ISSUE TITLE
How to achieve those awesome tooltips from the README?

### ISSUE THREAD

**Issue by tominventisbe** [gwomacks/php-debug#290]
I see in the README that there are overlay tooltips when hovering on variables when a breakpoint is triggered. I can't for the life of me seem to be able to get those. Do I perhaps need an additional package for it to work?

**Comment by cchamplin** [comment]
You'll need to install and configure the atom-ide and php-ide packages

**Comment by tominventisbe** [comment]
Ah, I see. Is this related to the showing of datatips? I see you use php-ide this to fetch the range of the datatip. Unfortunately, I'm using [Serenata](https://serenata.gitlab.io/) in Atom instead; is there no way to still have the debug evaluation available (I wouldn't mind losing some php-ide specific functionality)?

I took a look at how the Serenata package does it, and it appears ot [have its own function to fetch this range](https://github.com/Gert-dev/php-ide-serenata/blob/master/lib/SymbolHelpers.coffee). Hope this helps!
