### ISSUE TITLE
Closing both tabs via status bar buttons does not stop listening to XDebug

### ISSUE THREAD

**Issue by tominventisbe** [gwomacks/php-debug#291]
I do not have the "Continue to listen ... even if the debugger windows are all closed" option disabled, but even when I hide (perhaps this is the problem) both docks via their respective status bar buttons, breakpoints are still being triggered.

When I initially open the window, this is not the case. Perhaps the problem is that I am "hiding" the docks and not actually closing them?

**Comment by cchamplin** [comment]
This should be fixed in the next release (sometime this week). There is a flag that's sent to xdebug but to disable multiple connections but it looks like xdebug is ignoring this in certain situations.

**Comment by cchamplin** [comment]
Should be Fixed in v0.3.5. If not please reopen
