### ISSUE TITLE
0.3.4 SyntaxError Unexpected token U in JSON at position 45 at JSON.parse

### ISSUE THREAD

**Issue by msitarzewski** [gwomacks/php-debug#293]
Version 0.3.4 - I can't get a debugging session to work. I have ports forwarded from my debug server (port 9001) at Digital Ocean to local port 9002. This has worked flawlessly in the past, but after upgrading to 0.3.x it hasn't. Attached is a screenshot of the console when a debugging session is requested. All software versions are the latest: PHP 7.2.5, xdebug 2.6.0

The session seems to connect, but hangs, seemingly because of this error.

![screenshot 44](https://user-images.githubusercontent.com/1972242/39969791-1e8b1dba-56a7-11e8-9744-6a82870142e4.png)

**Comment by msitarzewski** [comment]
For what it's worth, this appears to be a Windows issue. The same setup works on macOS High Sierra.

**Comment by cchamplin** [comment]
Can you clear your php-debug config from config.cson and try again?

**Comment by msitarzewski** [comment]
Indeed, happy to. Tried again, and the position changed to 42 from 45. That doesn't appear to be helpful. I've updated the screenshot for you.
![screenshot 47](https://user-images.githubusercontent.com/1972242/40008702-903fa6ba-5765-11e8-86ad-249c16be0d12.png)

**Comment by cchamplin** [comment]
The error you're receiving is because the package is failing to parse your pathmaps. Can you provide your config here?

**Comment by msitarzewski** [comment]
"php-debug":
    showWelcome: false
    xdebug:
      pathMaps: "[{\"remotePath\":\"/var/www\",\"localPath\":\"C:\\Users\\msita\\OneDrive\\GitHub\"}]"
  welcome:
    showOnStartup: false

**Comment by cchamplin** [comment]
Hmm, I'm not sure how it would have been saved like that but it should look like

```json
"[{\"remotePath\":\"/var/www\",\"localPath\":\"C:\\Users\\msita\\OneDrive\\GitHub\"}]"
```
or 
```json
"[{\"remotePath\":\"/var/www\",\"localPath\":\"C:/Users/msita/OneDrive/GitHub\"}]"
```

**Comment by msitarzewski** [comment]
I noticed after you posted that the escaped back slashes were indeed escaped (they were there in the config file). When I pasted in the first option of yours, nothing changed (they were escaped). The second option didn't work, but I was prompted for a path setup for a file that runs in the apache config:

php_value auto_prepend_file "/var/www/bootstrap.php"

I told php_debug not to use that file/path, and it was added to the path config as expected:

"[{\"remotePath\":\"/var/www/ig\",\"localPath\":\"C:/Users/msita/OneDrive/GitHub/ig\"},{\"remotePath\":\"/var/www/bootstrap.php\",\"localPath\":\"!\"}]"

Now the sessions are being rejected all together. Can I just ignore it, not reject it?

![screenshot 50](https://user-images.githubusercontent.com/1972242/40012413-350e2ad6-5770-11e8-8f6b-cfc2746076c7.png)

**Comment by msitarzewski** [comment]
Solved. The issue was that I was only using single backslashes in the php_debug settings interface (resulting in double backslashes in the config.cson file). Once I added the second backslash in the interface (resulting in \\\\ in the config.cson) it worked!
