### ISSUE TITLE
Stopping only on gutter breakpoint

### ISSUE THREAD

**Issue by IRONALEKS** [gwomacks/php-debug#296]
I am not sure if it is a problem in the php-debug package, atom-debug-ui or atom-ide-ui package, i am not even sure that it is a problem but  when i install php-debug it recommends me to install atom-ide-ui and when i set the atom-ide-ui breakpoint(the left big one) it doesn't stop on it, but when i set the atom-debug-ui(the right small one) breakpoint it does stop on it, i am not sure if it is supposed to be like that, but in my opinion having two different types of breakpoints is a little weird, it would be cool if it used the atom-ide-ui(the big one) since it comes with the package that is part of facebook open source, i don't know how it works but maybe instead of atom-debug-ui, php-debug could use atom-ide-ui since it also has a debugger interface and is more maintained with 59 contributors, more than 1200 commits and around 30 releases, and maybe php-debug could one day become atom-ide-debugger-php as there are already atom-ide-debugger-node, atom-ide-debugger-python, atom-ide-debugger-react-native etc. which are also part of facebook-atom
![untitled](https://user-images.githubusercontent.com/17891257/40277494-763bd186-5c28-11e8-81e8-6b2c45d0fa7c.png)

**Comment by cchamplin** [comment]
@IRONALEKS atom-ide-ui has it's own separate debugger (for other languages not PHP so far). It looks like you are interacting with that debugger for your breakpoints and the breakpoints for PHP-Debug aren't getting set. You should be able to disable the atom-ide-ui debugger in the atom-ide-ui settings if you aren't using it.

At the moment there are no plans to integrate PHP-Debug with the atom-ide-ui debugger for various reasons.
