### ISSUE TITLE
Is this project discontinued? any alternative? 

### ISSUE THREAD

**Issue by jvlobo** [gwomacks/php-debug#314]
Hi there!

This project seems like is having a lot of bugs since the last update, the issues here in Github just keep increasing and the owner of the repo hasn't been here for a while.

Do you guys know any good alternative to debug PHP in Atom?

Cheers!

**Comment by cchamplin** [comment]
This project is not abandoned or discontinued. Unfortunately I have to split my time on other projects. Sometime in the next few weeks I should be able to address the issue backlog.

**Comment by jvlobo** [comment]
Thanks for the heads up.
Looking forward to see the updates
Thank you for your work.

Cheers!

**Comment by jvlobo** [comment]
Does anybody know any alternatives? :)

**Comment by lkraav** [comment]
I went with PhpStorm. It has its own quirks, but most mission critical stuff like debugging works great, and paid model has significantly better development alignment and velocity.
