### ISSUE TITLE
How do you "hook" up the debugger?

### ISSUE THREAD

**Issue by bobrocke** [gwomacks/php-debug#39]
Are there any instructions on how to get php-debug connected to Xdebug? On  a local site (no need or `PathMaps:`) breakpoints do not trigger.

**Comment by gwomacks** [comment]
Heyas.
I've included a bit more information on this on the [project page](https://github.com/gwomacks).

In brief, you need to
1. Ensure xdebug is installed and your settings are set up
2. Set a breakpoint and open up the debugging view (currently 'Toggle Debugging' in the menus)
3. Run the script. If you're not making use of the xdebug.remote_autostart function, you'll need one of the browser extensions to enable xdebug.

**Comment by bobrocke** [comment]
I do have Xdebug running and `phpinfo()` says so. When I attempt to set a breakpoint, the line number does not turn green. I assume that means no breakpoint has been set so when the debugger doesn't take control when the script is run, that must be why. I can toggle the debugger pane open.

What can I check to see why the breakpoint won't set?

**Comment by gwomacks** [comment]
Interesting. Does it show up in the last panel of the debugging view?
And what OS are you on?

**Comment by bobrocke** [comment]
I'm running Mac OS X 10.10.3.

I do see that breakpoint listed in the Breakpoints pane.

**Comment by luishdez** [comment]
I'm at the same situation
I see the breakpoints in the panel. But nothing happens.

I'm running OS X as well, and the php built-in server  `php -s … ` though I've tested with nginx+php-fpm and same result.

phpinfo();
```
xdebug.remote_autostart	On	On
xdebug.remote_connect_back	On	On
xdebug.remote_cookie_expire_time	3600	3600
xdebug.remote_enable	On	On
xdebug.remote_handler	dbgp	dbgp
xdebug.remote_host	127.0.0.1	127.0.0.1
xdebug.remote_log	no value	no value
xdebug.remote_mode	req	req
xdebug.remote_port	9000	9000
```

**Comment by gwomacks** [comment]
Dusted off my old macbook and found a few issues with path-handling. 
Should now be working in v0.0.11.

**Comment by luishdez** [comment]
Awesome! now it stops at the break points. though it's still a little bit buggy, second time I refresh the php Page it breaks at the marks but the continue button gets disabled…

**Comment by bobrocke** [comment]
OK! That's got it to work again. I'll open other issues as I find other problems.

**Comment by gwomacks** [comment]
Awesome, thank you. 
Now that the core functionality is there, I'm hoping to tackle all those small usability issues over the next few weeks

**Comment by sebzap** [comment]
I have this problem again with php-debug 0.1.3 on OS X 10.10.5. (I can toggle breakpoints put nothing happens.)

phpinfo();
```
xdebug.remote_autostart	On	On
xdebug.remote_connect_back	On	On
xdebug.remote_cookie_expire_time	3600	3600
xdebug.remote_enable	On	On
xdebug.remote_handler	dbgp	dbgp
xdebug.remote_host	127.0.0.1	127.0.0.1
xdebug.remote_log	no value	no value
xdebug.remote_mode	req	req
xdebug.remote_port	9090	9090
```

config.cson
```
"php-debug":
    ServerPort: 9090
```
