### ISSUE TITLE
Settings not saved or loaded (because of a case sensitive config name).

### ISSUE THREAD

**Issue by MineyMe** [gwomacks/php-debug#43]
Hello

It seems that on my system (Linux), my php-debug settings are not applied because of case sensitivity issues. Installing the extension and using the developer tools to check the name of the 'ServerPort' variable, I effectively see a value of 'undefined'. The cause of this seems to be that the code expects the config name to be **php-debug**, whilst Atom seems to have automatically called my config name **PHP-Debug** instead. Renaming all the occurences in the source code fixes the issue.

I'm not sure how atom extension developers should handle this, but I've reported the same issue for the termrk package, of which the author has resolved the issue in this commit [1], which may serve as a useful reference.

Thanks in advance

[1] https://github.com/romgrk/termrk/commit/26c1a8a9724b660265e867435e5e5c4a94eb3a51

**Comment by gwomacks** [comment]
Ah, that's interesting. I was going to have a look into what was going on with the default settings tonight,
I've noticed packages tend to prefer a lowercase name, so I'll likely look into getting the name changed to php-debug.

**Comment by gwomacks** [comment]
Name has been changed to php-debug, was fairly simple.
Thanks for your help.
