### ISSUE TITLE
Can't clear a breakpoint

### ISSUE THREAD

**Issue by bobrocke** [gwomacks/php-debug#45]
Toggling breakpoint will set one, but toggling it again does not clear it.

**Comment by Mrono** [comment]
Same here, tried with both keybindings and drop down menu.  Clearing all breakpoints does work, but that's everything.

**Comment by fobus42** [comment]
The same problem here. When I try to toggle a break point, it adds a new line in the "breakpoints"  tab.
So, I can add but can't remove breakpoint

**Comment by gwomacks** [comment]
Clearing individual breakpoints should now be working as of the latest version (v0.1.0)

**Comment by bobrocke** [comment]
It seems to be working for me. Thanks!

**Comment by fobus42** [comment]
It is working for me too, thanks
