### ISSUE TITLE
Esthetic Improvements

### ISSUE THREAD

**Issue by bobrocke** [gwomacks/php-debug#46]
A few suggestions:

Make a context menu for PHP Debug with submenu items for toggle breakpoint and toggle debugger.

Change the Packages>php-debug menu item to PHP Debug.

Divide the Packages>php-debug menu into groups. Maybe:
Toggle Debugging
Toggle Breakpoint
---
Run
Step Over
Step In
Step Out
---
Clear All Breakpoints
Clear All Watchpoints

**Comment by gwomacks** [comment]
Yep, I like these.
Will appear in the next release.
