### ISSUE TITLE
Can't watch nested arrays or objects

### ISSUE THREAD

**Issue by fobus42** [gwomacks/php-debug#47]
I have some arrays and objects that has 6-7 deep. But Php Debug only shows the first and second step variable in array-object.

I would want to track all sub values. Does not this plugin support this?

Thanks all.

**Comment by gwomacks** [comment]
atm it's not possible. I can probably fit in a configuration setting for
this in the next release.

**Comment by fobus42** [comment]
@gwomacks Thank you for your interest.

**Comment by gwomacks** [comment]
Implemented in the latest released. Defaults Max Depth of 8, can be configured in the settings for the package.
