### ISSUE TITLE
Debugger freezes screen

### ISSUE THREAD

**Issue by fobus42** [gwomacks/php-debug#48]
Hello,

I'm opening debugger window, and running the script. and then window is freezing. I'm not able to click on any button. 

Waiting for 1-2 minutes, then asking to close window. 

This error occured after the last update.

**Comment by gwomacks** [comment]
Yeah, I'm looking into this one now. Seems to be struggling with nested variables.
Changing Max Children to 32 and Max Depth to 4 sped rendering up a fair bit.  
I'll likely make those the defaults in the next version, while I look into ways of speeding it up.

**Comment by fobus42** [comment]
@gwomacks this is the best support for an open source project that I have seen ever.
Thank you!

**Comment by fobus42** [comment]
Max Children and Max Depth 4 works great with the last update. 
Thank you!
