### ISSUE TITLE
Request - Ability to copy Watchpoint values

### ISSUE THREAD

**Issue by fobus42** [gwomacks/php-debug#51]
It would be great if I could copy the value of a Watchpoint item. I'm able to select the text, but CTRL+C doesn't work. Also right click doesn't show "Copy" command.

Thanks.

**Comment by gwomacks** [comment]
Yeah, I was surprised when I first tried it and it didn't just worked.  
I've added ctrl-c to copy in the latest version. I'll likely do something with the right click menu later down the track.
