### ISSUE TITLE
Can't continue after second refresh in browser

### ISSUE THREAD

**Issue by luishdez** [gwomacks/php-debug#52]
I'm using OS X Yosemite.

the first time I execute the script using the browser with autostart, it works ok, but at the end the button Continue gets disabled and if I refresh the browser, breakpoints work, but I'm not able to continue.

If I enable the button with the inspector I get `cannot read continue property … `

Thanks a lot :) this plugin is promising

**Comment by willembressers** [comment]
i'm experiencing the same issue.. In Ubuntu

Not sure, why / how.. But if i kill Atom and restart it, the page can be refreshed.

**Comment by cchamplin** [comment]
Over a year old, closing. If this is still an issue feel free to reopen.
