### ISSUE TITLE
Looking for help setting the plugin

### ISSUE THREAD

**Issue by lmartins** [gwomacks/php-debug#53]
Hi,

I was hoping for something like this for a long time, thank you much.
That being said, I do need some help setting it up. 
Im debugging a PHP app (WordPress) running over a Vagrant VM. That VM has x-debug enabled and when I launch the debugger I do get all the vars and stack listed in Atom. But I also do get the following error:

`The linter binary 'php' cannot be found.`

Mind you I haven't yet added the following to my config.cson, as im not sure what to point those paths to:

```cson
"php-debug":
  {
    ServerPort: 9000
    PathMaps: [
      {
        local: "C:\\base\\path\\on\\local\\system"
        remote: "/base/path/on/remote/system"
      },
      {
        local: "C:\\another\\path\\map"
        remote: "/home/yay/"
      }
    ]
  }
```

Could you please help me out with this?
Many thanks.

**Comment by gwomacks** [comment]
That error doesn't seem like a php-debug error to me. When does the error appear? And what other packages do you have installed?  
I'm guessing one requires php installed on your local machine (same machine atom is running on), to do some sort of code validation. 

The path map stuff, it pretty much takes the path of the file, looks for the "from" string and replaces it with with the "to" string, to figure out what file on the local machine to open.  
Atm it won't work well if such a translation doesn't make sense (ie not got the project directory mounted on your local machine), but I'm planning to add some flexibility for that soon.

**Comment by lmartins** [comment]
The error appears when the php code first runs.
But those paths should point to the website root, the php binary, or something else?

**Comment by gwomacks** [comment]
Remote is the website project root.
Local is a path on your workstation.

For example, on my remote box I have the file: /home/gabriel/projects/site/example.php
On my local machine, this maps to: G:\projects\site\example.php

in this case me config.json would look like:
"php-debug":
  {
    ServerPort: 9000
    PathMaps: [
      {
        local: "G:\\projects\\"
        remote: "/home/gabriel/projects/"
      }
    ]
  }

**Comment by wouterds** [comment]
Can't seem to get it working with Vagrant.
Some help or documentation would be nice.
