### ISSUE TITLE
Breaks on every notice/deprecation

### ISSUE THREAD

**Issue by moolen** [gwomacks/php-debug#54]
php-debug breaks on every notice/deprecation warning. Is there a way to get around this. Im debugging a old shop-system and there is no way to get around the deprecation warnings and notices.
setting the error_reporting and display_errors does not help.

While using the XDebug extension [1] for chrome notices or deprecation warnings do not produce a break.

Do you have any idea?

[1] https://chrome.google.com/webstore/detail/xdebug/nhodjblplijafdpjjfhhanfmchplpfgl?hl=en

**Comment by gwomacks** [comment]
Check out the settings for the php-debug package, there's a bunch of
checkboxes related to php exceptions that you can uncheck to disable this
behaviour.

**Comment by moolen** [comment]
alright, thanks!
