### ISSUE TITLE
No output listed in views?

### ISSUE THREAD

**Issue by Gert-dev** [gwomacks/php-debug#56]
Hello

Since around version 0.1.0 (can't remember exactly), whenever a breakpoint or exception is triggered, I see the toolbar buttons in light up and the page waits for the continue signal to be sent, but I can't see any output in the views themselves (i.e. there are no variables listed, no stack trace, etc. in the views). Also, sometimes I press the continue button and the buttons grey out, but the page still hangs. In this case however the breakpoint is triggered very quickly again after the previous contnue, could it be that it happened too fast for php-debug to pick it up?

If this is an issue on my side or you would like me to try something, feel free to let me know. The debug views did work correctly in the first versions of the plugin.

Thanks in advance

**Comment by Gert-dev** [comment]
This is fixed in the latest release (0.2.0) for me, thanks!

**Comment by Gert-dev** [comment]
Unfortunately this seems to be broken again in 0.2.1. Either this or it randomly works sometimes and fails other times. I tried a couple of times with the new version and also tried thing such as restarting Atom, but the problem seems to persist.

**Comment by cchamplin** [comment]
The next time this occurs can you open the atom developer console and provide any additional information it provides?

**Comment by Gert-dev** [comment]
I did some more debugging and the problem seems to be linked to a specific project. In one project I can debug fine using the current version and the previous. In another I can't. The strange thing is that both projects use the same PHP version and Xdebug version, i.e. there should be no difference. They are also set up the same way in Apache and use the same framework.

The console logs "Listening on port 9000" and "Session initiated". The logged `init` object indicates my xdebug version is 2.3.3. In the failing project, the breakpoint is still triggered, but no output is listed. When I press the Continue button, I get over 100 messages stating 'New session rejected' and the page keeps loading infinitely in the browser. If I then reload the page, it loads fine and php-debug outputs another 100-ish 'New session rejected' messages. At that point the breakpoints also don't trigger anymore (i.e. nothing works at this point until I restart Atom).

**Comment by Gert-dev** [comment]
Strangely enough, it seems to be solved in 0.2.2, at least the few times I tried again.
