### ISSUE TITLE
Bring Atom to front on hitting a breakpoint

### ISSUE THREAD

**Issue by philiplb** [gwomacks/php-debug#61]
Hi,

it would be neat if the plugin could take care of bringing Atom into front when a breakpoint is triggered. This way I don't have to questimate when this happens on navigating the application in the browser, I would instantly know when the debugger kicks in.

**Comment by cchamplin** [comment]
I believe there is a pull request for this, waiting for it to be split out and then will get it merged in.

**Comment by StAmourD** [comment]
#190 merged with 0.2.4
