### ISSUE TITLE
Breakpoints not highlighted

### ISSUE THREAD

**Issue by davycheung** [gwomacks/php-debug#66]
Not sure if this is just a setting on my machine but when setting a break point, the line of code is not highlighted. I can see that I set them by going into debug mode (see screenshot). Running on Windows 7.

![7-21-2015 4-06-24 pm](https://cloud.githubusercontent.com/assets/4220987/8811218/7fffde0a-2fc2-11e5-8ae4-f5a0cedad2c4.png)

**Comment by imperez** [comment]
I'm getting the same issue. It seems like a bug where the breakpoint isn't getting set at all since the code is never stopped at the breakpoint.

**Comment by davycheung** [comment]
The breakpoints are working for me (code stops executing), but I don't see the highlighting on the code itself.

**Comment by imperez** [comment]
Ah ok. Then I might have some configuration wrong. I assumed it was related since the breakpoints were working at one point and then stopped.

**Comment by ChristianGrech** [comment]
+1

**Comment by MacsDickinson** [comment]
+1

I get the same. Breakpoints work but they are not highlighted. I'm also running on Windows.

**Comment by fpm5022** [comment]
+1

**Comment by Elexy** [comment]
+1

**Comment by vrash** [comment]
+1 on Mac

**Comment by sheikh-aamir** [comment]
Same issue on windows 10 and Atom 1.0.7

**Comment by YagoQuinoy** [comment]
+1

**Comment by cchamplin** [comment]
Can anyone confirm if this issue has been fixed with the plugin 1.0.3 release?

**Comment by davycheung** [comment]
Looks good on Windows 10 & OSX (Yosemite).
