### ISSUE TITLE
Allow for multiple active debugging sessions

### ISSUE THREAD

**Issue by gwomacks** [gwomacks/php-debug#7]

**Comment by stianborgesen** [comment]
I think I have a problem related to this. If this feature is missing.

I have a php page doing an ajax request immediately after requesting the page. To be able to breakpoint the ajax request I have to breakpoint my front-end client before the ajax request is executed, and then wait for a while, and let it execute. This makes the interval between the page load request and the ajax request longer, and it is the only way I am able to successfully activate a breakpoint on the server side for that ajax request. If I just let the font-end client do the ajax request immediately after the page load, the breakpoint on the server is never activated.

Could this be defined as multiple connections use-case? If so, is the absents of this feature causing my problems?

**Comment by cchamplin** [comment]
Fixed in v3.0.0
