### ISSUE TITLE
Cli script

### ISSUE THREAD

**Issue by Elexy** [gwomacks/php-debug#70]
I have been able to debug local and remote server (fpm) scripts but I can't seem to find a way to debug a local phpunit cli session.

I am running this from a script file on my linux dev box:
```
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
export XDEBUG_CONFIG="idekey=session_name remote_host=localhost profiler_enable=1"
php $DIR/../vendor/phpunit/phpunit/phpunit --stderr $@
``` 
which works for the debugger in PHPSTORM but not for this one.

Does anyone have an idea?

**Comment by Elexy** [comment]
This can be closed.
It just works when i set an xdebug_break() in my code.
Toggle breakpoint is invisible and also not caught. But this is unrelated.

**Comment by OZZlE** [comment]
why close it? we should be able to debug cli scripts as well..? also your workaround doesn't work for me `xdebug_break()` is undefined
