### ISSUE TITLE
Breakpointing works but debugging panel never activates.

### ISSUE THREAD

**Issue by synthecypher** [gwomacks/php-debug#72]
I have a problem where I'll create a breakpoint and the line where the breakpoint is will highlight but the debugging panel doesn't become active. Meaning the buttons that enable continuing and stepping over lines of code are still greyed out. Also the *Stack* and *Context* sections are blank and don't show the local/global scope.

I really love this atom package but it seems really unreliable one day it'll work no problem and the next it'll be broken.

**Comment by synthecypher** [comment]
I just updated to v0.1.3 and now the highlighting of the breakpoint in the gutter works but breakpoints don't work anymore.

**Comment by cchamplin** [comment]
Can you let me know if v0.1.4 solves this?

**Comment by driskell** [comment]
I've found that when breakpoints aren't working at all it's because the mapping was incorrect and I'd set the breakpoint on a file that didn't map properly to the server side, so it never actually interrupted execution. Don't know if this might help?
