### ISSUE TITLE
Memory leak when stepping through code.

### ISSUE THREAD

**Issue by pwillcode** [gwomacks/php-debug#73]
Any time the debugger stops (at a breakpoint, or after stepping) some memory is leaked.
To demonstrate this, step through the following test script.
>for ($i = 0; $i < 100; $i++) {
>  echo 'Break here to add to the memory leak.';
>}

Just click through all 100 breaks, and watch the memory footprint of atom steadily rise (about 40 megs for me.)

Note that this is just about best-case. When I first discovered this at work, I was getting 10 megs leaked per break, which leads to disk swapping after just a couple minutes of using the debugger.

The memory persists between debugging sessions and only frees when I quit out of Atom entirely.

I tried to find the memory leak on my own, but didn't have a whole lot of luck.
The only obvious thing I noticed is that an object is being [logged to the console](https://github.com/gwomacks/php-debug/blob/master/lib/engines/dbgp/dbgp-instance.coffee#L193) each time a breakpoint hits, and I have read that this prevents garbage collection. This, however, can't account for all of the leakage.

Most of the leaked memory appears to be compiled code.
![image](https://cloud.githubusercontent.com/assets/6126513/9571187/8603ba28-4f4e-11e5-9896-9c9a77502d82.png)
I tried to look into that, but couldn't make any easy progress.

**Comment by cchamplin** [comment]
If this is still an issue please reopen. Closing for now because of all the changes to atom and php-debug since the issue was created.
