### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by rgeddes** [gwomacks/php-debug#74]
-  The debugger controls pop up in a different panel and a tab called "Debugging".  As it steps into another file using the control buttons, a new tab in the same panel is created to display the current execution line.  That tab is auto selected to view the code ( this is not a good idea ), and while switching back and forth between the Debugger tab and the source tab, the control buttons disappeared.  To get them to re-appear, I moved the Debugger tab relative to the source tabs.  To avoid this issue I used the keyboard short cuts with the focus on the non-Debugger panel.

- It would be better to always display the source in the original panel where the breakpoints are set, separate from the Debugger panel for stepping with the mouse.

- Each time I step the execution, all containers in the Context pane close up.  If I want to monitor the state of values in a container while stepping, I have to continually open the container while stepping.  Same applies to  containers in Watchpoints.

- Editable Watchpoints... edit and delete.

- I think it's already mentioned, but stack frames are not selectable, so debugging is limited to only the current stack frame.  Opening up the state of all stack frames for inspection is very useful.

- It would be nice to be able to move ( drag and drop ) the Debugger panel on the screen at any time.

**Comment by driskell** [comment]
Regarding point 1, I've raised PR #96 which experiments moving Debugger tab to a bottom panel like the Linter. It'll be great to hear some feedback. The maintainer hasn't had a look yet but hoping they will soon.

**Comment by cchamplin** [comment]
Thanks for the feedback, many of these things have been addressed.
