### ISSUE TITLE
Need help setting up

### ISSUE THREAD

**Issue by ArakTaiRoth** [gwomacks/php-debug#76]
Just wondering if I can get some assistance in setting this up. I'm using a windows machine (Windows 8) to connect to an application running on a windows server (Windows Server 2012 R2).

I have the php.ini set up as stated on this page https://atom.io/packages/php-debug. I have checked my phpinfo, and XDebug is loaded and running. I have set the firewall on the server to allow both incoming and outgoing on Port 9000. In my config.cson I have some pathmaps setup, local is just to the local folder that I am programming in, remote is to a network attached drive that references the exact same code I'm working on in my local folder. I'm using the chrome xdebug helper extension.

I've noticed that when I first checked my phpinfo, my IDE Key was something weird, after I tried debugging with atom, it changed to XDEBUG_ATOM. So some communication must be happening, but my line breaks aren't being triggered. I'm not quite sure what I'm doing wrong, and was hoping someone might be able to help me out.

**Comment by wallter** [comment]
+1 

**$ php -v**
```
PHP 5.6.13-1+deb.sury.org~trusty+3 (cli) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Xdebug v2.3.2, Copyright (c) 2002-2015, by Derick Rethans
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
```

**/etc/php5/cli/php.ini**  &nbsp;&nbsp; && &nbsp;&nbsp;  **/etc/php5/apache2/php.ini**
```
[Xdebug]
xdebug.remote_enable=1
xdebug.remote_host=127.0.0.1
xdebug.remote_connect_back=1    # Not safe for production servers
xdebug.remote_port=9000
xdebug.remote_handler=dbgp
xdebug.remote_mode=req
; xdebug.remote_autostart=true
xdebug.remote_autostart=false

zend_extension="/usr/lib/php5/20131226/xdebug.so"
```

**Comment by cchamplin** [comment]
This issue is over a year old, if you are still experiencing issues with the latest release please reopen.
