### ISSUE TITLE
Performace Problems On i5 6 GB Notebook

### ISSUE THREAD

**Issue by fobus42** [gwomacks/php-debug#80]
Hello,

I have a I5 and 6GB Linux system that runs Atom with php-debug. While I am debuging executing one line code gets 1 seconds. So, I'm pressing "step over" and waiting 1 seconds.

Max Children : 16
Max Depth : 3

Those values are less than the default values, but still I have performance issues.

**Comment by fobus42** [comment]
I have just imagined that, delay is is not 1 seconds. It is allways more than 2 seconds.

**Comment by sillyslux** [comment]
> I have just **imagined** that, delay is is not 1 seconds. It is allways more than 2 seconds.

Are you still _imagining_ this performance issue?

If your not just imagining but experiencing, could be due to a poor connection to the server. Where is the server location? Remote or local (virtualized or localhost)?

**Comment by fobus42** [comment]
Hah, My poor English :) I didn't imagined it I have experienced it.

I have gave up using Atom, because the most important point is debugging for me, and it is not possible to debug with Atom.

Answeer : I was trying to debugging in a local computer, it was not remote.

Thank you!
