### ISSUE TITLE
Breakpoint line number is not highlighted in green

### ISSUE THREAD

**Issue by tbitai** [gwomacks/php-debug#81]
![image](https://cloud.githubusercontent.com/assets/6923611/10238632/901129dc-68c2-11e5-8dd3-8996510db90a.png)

Line 46 on the screenshot is a breakpoint, but it's not highlighted.

I don't know what info of my system is relevant here, pls ask.

**Comment by dx17** [comment]
+1 
same here using 
Mac OS X 10.11, 
Atom 1.0.19, 
php-debug 0.1.3

Thanks

**Comment by tbitai** [comment]
I'm using php-debug 0.1.3 and Atom 1.0.19 too, on Arch Linux.

**Comment by doliver3** [comment]
I have the same issue with a brand new install of Atom with only the php-debug package added to the defaults.  I can see that the breakpoint gets set in the breakpoint list, and it will stop on the breakpoint, but there is no indication on the line where the breakpoint is set - no green color or anything in the margin.  I have Mac OS 10.10.5

**Comment by kalinchernev** [comment]
Same issue with php-debug 0.1.3, Atom 1.0.19 and xubuntu 14.04 and xfce 4.12

**Comment by tharris-fps** [comment]
Same Issue Ubuntu 14.04 atom 1.0.19 php-debug 0.1.3

**Comment by cchamplin** [comment]
Possibly fixed with #86

**Comment by dx17** [comment]
@cchamplin 

thanks, debug breakpoint is visible now.

**Comment by damiann** [comment]
@cchamplin thanks!
