### ISSUE TITLE
Option to split the debugging pane from the top pane.

### ISSUE THREAD

**Issue by Gert-dev** [gwomacks/php-debug#91]
Hello

Currently the debugging pane seems to take the active pane and split it halfway vertically, using the bottom half to display itself:

```
---------------
| Editor      |
|             |
|-------------|
| Debug pane  |
---------------
```

However, when using a (horizontal) split view, it will fill half of the screen horizontally and reuse the bottom half of the left pane:

```
----------------------------
| Editor      | Editor     |
|             |            |
|-------------|            |
| Debug pane  |            |
|-------------|------------|
```

It would be useful if instead of using the current pane, the package tried to use the topmost pane and divide that vertically, that way the debug pane fills the entire window horizontally instead of just half (which is useful as it contains a lot of content that can benefit from the additional horizontal space):

```
----------------------------
| Editor      | Editor     |
|             |            |
|--------------------------|
| Debug pane               |
|--------------------------|
```

Thanks in advance

**Comment by driskell** [comment]
Take a look at #96 - I've been experimenting with a bottom panel and raised a PR for the maintainer to have a look at.

**Comment by cchamplin** [comment]
@driskell's changes have been published in the latest release.

**Comment by Gert-dev** [comment]
More than sufficient for me, thanks!
