### ISSUE TITLE
Debugger doesn't pause at breakpoints

### ISSUE THREAD

**Issue by NicholasJohn16** [gwomacks/php-debug#97]
I'm having an issue was hoping I could get some help with configuring Atom and Xdebug. I can set breakpoints and they show up in the breakpoint panel, but the process never pauses. Oddly, the process does pause on a exception warning, so I know it's connecting somewhat, but just not pausing at breakpoints.

My php.ini is as described in the readme:
```
    xdebug.remote_enable=1
    xdebug.remote_host=127.0.0.1
    xdebug.remote_connect_back=1    # Not safe for production servers
    xdebug.remote_port=9000
    xdebug.remote_handler=dbgp
    xdebug.remote_mode=req
    xdebug.remote_autostart=true
```
Here's my settings:
```
    "php-debug":
        PhpException:
          Warning: false
        PathMapping: [
          {
            local: "C:\\wamp\\www\\sgn\\com-forums\\www\\index.php"
            remote: "localhost/sgn/com-forums/www/index.php"
          }
        ]
```
I'm developing locally using WAMP, xdebug 2.3.5, Atom 1.2.3, & php-debug 0.1.4. As well, I'm using Chrome with Xdebug helper. What should the idekey be? Any ideas why it isn't working?

**Comment by cchamplin** [comment]
This has been adjusted with the latest release. The new format is "remotepath;localpath".

Your Example would be 
```cson
PathMaps: [
  "localhost/sgn/com-forums/www/index.php;C:\\wamp\\www\\sgn\\com-forums\\www\\index.php"
]
```
