### ISSUE TITLE
Debugging Tab scrolling & hiding the buttons

### ISSUE THREAD

**Issue by rzelnik** [gwomacks/php-debug#98]
I use Atom on Ubuntu 15:10. The Debugging tab is a bit higher than it's space in the Atom window in any height, so it allows scrolling of the whole tab - see picture 1.
![php-debug1](https://cloud.githubusercontent.com/assets/610651/11334195/c16af7ee-91d3-11e5-93be-06eb23c1f603.png)
When I scroll the Debugging tab by mistake (which occurs quite often), it causes hiding the buttons (Continue, Step Over, Step In, ...) - see picture 2.
![php-debug2](https://cloud.githubusercontent.com/assets/610651/11334231/055e435c-91d4-11e5-9b77-d1bb3a758e35.png)

**Comment by cchamplin** [comment]
This should be corrected in the latest release.
