### ISSUE TITLE
Trying to set PathMaps

### ISSUE THREAD

**Issue by Leuloch** [gwomacks/php-debug#99]
How should I put the paths in the config? (remote and local)

**Comment by socket462** [comment]
Me also is looking into this.
Without remote debugging is impossible and extension not very useful.

Anyway keep up the good work

**Comment by derekderaps** [comment]
I believe the real problem is in Atom core. I made an issue there: https://github.com/atom/atom:10345

**Comment by stuwilliams47** [comment]
Is this an issue with a specific version of Atom? Can I get round it by using an older version?

**Comment by derekderaps** [comment]
>Is this an issue with a specific version of Atom? Can I get round it by using an older version?

Not that I'm aware of. For now, I switched back to [PHPStorm](https://www.jetbrains.com/phpstorm/) for debugging. I don't prefer developing in PHPStorm, but it's debugger is amazing.

**Comment by cchamplin** [comment]
This has been adjusted with the latest release. The new format is "remotepath;localpath". This should fix remote debugging
